package uk.co.tjcdeveloper.opencoloursort.levels

/**
 * GENERATED by BakeLevelsTool from PackPlan - do not edit by hand.
 * Every level is solver-verified solvable; classic levels sit inside
 * their PackPlan min-moves and dead-state bands.
 * Encoding: one string per tube, colour keys bottom -> top.
 */
object GeneratedLevels {
    /** Packs 1-10 in play order, 40 levels each. */
    val classic: List<List<List<String>>> = listOf(
        // Pack 1 - Beginner
        listOf(
            // P1 L1: 3c 2e, min 6 moves, dead 0.0% (seed 10002)
            listOf("ooyy", "yrro", "rryo", "", ""),
            // P1 L2: 3c 2e, min 7 moves, dead 0.0% (seed 10003)
            listOf("ooro", "yrro", "ryyy", "", ""),
            // P1 L3: 3c 2e, min 6 moves, dead 0.0% (seed 10005)
            listOf("yroo", "roor", "ryyy", "", ""),
            // P1 L4: 4c 2e, min 9 moves, dead 0.0% (seed 10007)
            listOf("yory", "ygrr", "rggg", "oyoo", "", ""),
            // P1 L5: 4c 2e, min 8 moves, dead 0.0% (seed 10008)
            listOf("ooog", "oygr", "grrg", "yyyr", "", ""),
            // P1 L6: 4c 2e, min 10 moves, dead 0.0% (seed 10009)
            listOf("gggo", "ooyr", "orgy", "ryry", "", ""),
            // P1 L7: 4c 2e, min 10 moves, dead 0.0% (seed 10012)
            listOf("ryyr", "gggo", "oroy", "ogry", "", ""),
            // P1 L8: 4c 2e, min 8 moves, dead 0.0% (seed 10020)
            listOf("oyrr", "ggrr", "yoyy", "goog", "", ""),
            // P1 L9: 5c 2e, min 14 moves, dead 0.3% (seed 10027)
            listOf("rbyo", "royb", "yyog", "rrbg", "bogg", "", ""),
            // P1 L10: 5c 2e, min 12 moves, dead 0.5% (seed 10030)
            listOf("oygy", "ggbb", "rrog", "rrob", "byoy", "", ""),
            // P1 L11: 5c 2e, min 13 moves, dead 1.7% (seed 10033)
            listOf("ogrr", "bryy", "bogg", "yygb", "obor", "", ""),
            // P1 L12: 5c 2e, min 14 moves, dead 3.7% (seed 10053)
            listOf("yror", "ggyb", "rryo", "obbo", "gbgy", "", ""),
            // P1 L13: 5c 2e, min 14 moves, dead 3.1% (seed 10122)
            listOf("gbyo", "broy", "oyob", "grrr", "bggy", "", ""),
            // P1 L14: 5c 2e, min 13 moves, dead 2.2% (seed 10125)
            listOf("bybr", "ggby", "oorg", "oyyg", "orrb", "", ""),
            // P1 L15: 6c 2e, min 16 moves, dead 2.6% (seed 10127)
            listOf("ygpp", "rbob", "gyrr", "ogbb", "yrgp", "ypoo", "", ""),
            // P1 L16: 6c 2e, min 16 moves, dead 1.9% (seed 10128)
            listOf("gbbb", "grpy", "ygor", "ppob", "yygo", "porr", "", ""),
            // P1 L17: 6c 2e, min 16 moves, dead 1.2% (seed 10132)
            listOf("orpy", "pyyp", "oggy", "gpbo", "gbrr", "robb", "", ""),
            // P1 L18: 6c 2e, min 18 moves, dead 0.9% (seed 10134)
            listOf("rgpo", "bbor", "gypy", "rbyg", "yobp", "ogrp", "", ""),
            // P1 L19: 6c 2e, min 18 moves, dead 1.5% (seed 10135)
            listOf("yroy", "prbo", "rygp", "robp", "bbgg", "gpyo", "", ""),
            // P1 L20: 6c 2e, min 17 moves, dead 2.5% (seed 10136)
            listOf("rrog", "rgby", "ybpg", "ooby", "rbgo", "yppp", "", ""),
            // P1 L21: 6c 2e, min 17 moves, dead 2.0% (seed 10137)
            listOf("gpyy", "ggor", "pboy", "rorp", "ybbp", "obrg", "", ""),
            // P1 L22: 6c 2e, min 16 moves, dead 1.8% (seed 10144)
            listOf("bbbg", "pgrr", "gyoy", "gryr", "opyo", "oppb", "", ""),
            // P1 L23: 6c 2e, min 19 moves, dead 3.9% (seed 10146)
            listOf("ppyb", "gory", "popo", "gyry", "bgrg", "obrb", "", ""),
            // P1 L24: 6c 2e, min 19 moves, dead 3.6% (seed 10148)
            listOf("yrop", "pgpb", "ybro", "grpy", "goob", "bryg", "", ""),
            // P1 L25: 6c 2e, min 18 moves, dead 5.1% (seed 10153)
            listOf("ggbb", "oyrp", "pybr", "gyor", "obpp", "gryo", "", ""),
            // P1 L26: 6c 2e, min 16 moves, dead 5.6% (seed 10155)
            listOf("gorr", "bypb", "groo", "rpyy", "bbyg", "pogp", "", ""),
            // P1 L27: 6c 2e, min 17 moves, dead 5.4% (seed 10157)
            listOf("gpop", "rrog", "bbrg", "pyob", "rpyo", "gbyy", "", ""),
            // P1 L28: 6c 2e, min 18 moves, dead 4.9% (seed 10165)
            listOf("roog", "obyp", "rybb", "rboy", "rgpp", "gpgy", "", ""),
            // P1 L29: 6c 2e, min 19 moves, dead 5.2% (seed 10167)
            listOf("pbgg", "rpyo", "bopr", "byyr", "gbog", "rpoy", "", ""),
            // P1 L30: 6c 2e, min 17 moves, dead 3.9% (seed 10181)
            listOf("pbro", "yypb", "ogpp", "rybr", "ggoy", "orbg", "", ""),
            // P1 L31: 6c 2e, min 20 moves, dead 5.1% (seed 10185)
            listOf("gryb", "opop", "byyg", "grbr", "pbrp", "oygo", "", ""),
            // P1 L32: 6c 2e, min 18 moves, dead 5.3% (seed 10189)
            listOf("gypy", "pogb", "rrby", "byrb", "rgop", "pgoo", "", ""),
            // P1 L33: 6c 2e, min 18 moves, dead 5.5% (seed 10195)
            listOf("gpoo", "yrpg", "rpog", "bpry", "ogyr", "bbyb", "", ""),
            // P1 L34: 6c 2e, min 20 moves, dead 5.5% (seed 10197)
            listOf("gpgo", "goob", "gybr", "rpoy", "bryp", "rpyb", "", ""),
            // P1 L35: 6c 2e, min 20 moves, dead 6.6% (seed 10200)
            listOf("bppy", "gpoy", "oprb", "grgr", "yrbo", "ogby", "", ""),
            // P1 L36: 6c 2e, min 20 moves, dead 5.4% (seed 10217)
            listOf("ogbo", "opyb", "rpro", "rrgy", "pgyg", "pbyb", "", ""),
            // P1 L37: 6c 2e, min 19 moves, dead 6.8% (seed 10225)
            listOf("yrgb", "rbpb", "poyo", "ppgy", "ogor", "rbyg", "", ""),
            // P1 L38: 6c 2e, min 18 moves, dead 6.9% (seed 10230)
            listOf("ypgr", "ybbr", "gbpb", "poyg", "grpo", "oory", "", ""),
            // P1 L39: 6c 2e, min 19 moves, dead 7.3% (seed 10232)
            listOf("byop", "brpg", "ygyb", "boop", "rrgp", "rogy", "", ""),
            // P1 L40: 6c 2e, min 20 moves, dead 7.4% (seed 10234)
            listOf("pgog", "oybp", "prbb", "ogyr", "pryb", "gryo", "", ""),
        ),
        // Pack 2 - Easy 1
        listOf(
            // P2 L1: 6c 2e, min 18 moves, dead 3.9% (seed 20004)
            listOf("ypgp", "bobb", "ogyr", "oyrg", "rrpo", "bgyp", "", ""),
            // P2 L2: 6c 2e, min 18 moves, dead 3.7% (seed 20007)
            listOf("rybb", "yboy", "ogpg", "grpr", "goby", "popr", "", ""),
            // P2 L3: 6c 2e, min 17 moves, dead 5.5% (seed 20009)
            listOf("yopy", "rppr", "bypr", "oygo", "brgg", "ogbb", "", ""),
            // P2 L4: 6c 2e, min 17 moves, dead 5.9% (seed 20015)
            listOf("bppb", "robg", "rpyp", "gbyo", "yroo", "yrgg", "", ""),
            // P2 L5: 6c 2e, min 18 moves, dead 3.2% (seed 20019)
            listOf("ogrr", "ybbr", "yrgp", "goyg", "obpp", "obyp", "", ""),
            // P2 L6: 6c 2e, min 18 moves, dead 3.3% (seed 20021)
            listOf("oopg", "bpgb", "orpp", "brgg", "ybyr", "yoyr", "", ""),
            // P2 L7: 6c 2e, min 18 moves, dead 3.7% (seed 20023)
            listOf("gbgb", "opgb", "rryy", "rbop", "yrop", "yogp", "", ""),
            // P2 L8: 6c 2e, min 17 moves, dead 4.4% (seed 20024)
            listOf("opry", "gbgg", "ygpb", "rybo", "oorb", "rypp", "", ""),
            // P2 L9: 6c 2e, min 18 moves, dead 6.5% (seed 20028)
            listOf("bopb", "robr", "pryy", "pyrg", "gygp", "bgoo", "", ""),
            // P2 L10: 6c 2e, min 17 moves, dead 6.1% (seed 20036)
            listOf("obyy", "rrpo", "obyg", "bpyb", "opgg", "grpr", "", ""),
            // P2 L11: 6c 2e, min 18 moves, dead 5.7% (seed 20042)
            listOf("oybg", "bbrp", "gppg", "opoy", "byor", "yrgr", "", ""),
            // P2 L12: 6c 2e, min 18 moves, dead 5.8% (seed 20043)
            listOf("yogb", "yrgb", "yppr", "bgop", "oobr", "grpy", "", ""),
            // P2 L13: 6c 2e, min 18 moves, dead 6.7% (seed 20059)
            listOf("rpgb", "byob", "borp", "ggyy", "gyoo", "rprp", "", ""),
            // P2 L14: 6c 2e, min 18 moves, dead 7.0% (seed 20062)
            listOf("yrog", "rbpg", "ybbr", "ryoo", "ggpb", "ypop", "", ""),
            // P2 L15: 6c 2e, min 20 moves, dead 5.5% (seed 20073)
            listOf("oygo", "ropg", "rbog", "bybg", "rpbp", "ryyp", "", ""),
            // P2 L16: 6c 2e, min 19 moves, dead 6.3% (seed 20081)
            listOf("bypb", "rryp", "opoy", "obgg", "byrp", "rgog", "", ""),
            // P2 L17: 7c 2e, min 23 moves, dead 5.5% (seed 20086)
            listOf("bgog", "yprb", "ytbr", "bypo", "gpto", "ytgo", "prrt", "", ""),
            // P2 L18: 7c 2e, min 21 moves, dead 4.0% (seed 20087)
            listOf("troy", "bbgp", "tobg", "ygyr", "obrp", "ppty", "gtor", "", ""),
            // P2 L19: 7c 2e, min 22 moves, dead 7.8% (seed 20090)
            listOf("bgpo", "tgyo", "btrr", "pbto", "ggpy", "rbop", "tyry", "", ""),
            // P2 L20: 7c 2e, min 21 moves, dead 7.3% (seed 20092)
            listOf("tgby", "rpgg", "ygyr", "pbyb", "totp", "rpoo", "obrt", "", ""),
            // P2 L21: 7c 2e, min 21 moves, dead 6.0% (seed 20095)
            listOf("bpgr", "bptg", "prto", "pory", "ybor", "yytt", "ggbo", "", ""),
            // P2 L22: 7c 2e, min 22 moves, dead 4.5% (seed 20098)
            listOf("poyr", "oryp", "grbt", "pygt", "bgpg", "oort", "tbby", "", ""),
            // P2 L23: 7c 2e, min 20 moves, dead 5.9% (seed 20100)
            listOf("gorr", "yytp", "gopg", "pbpb", "yytg", "trob", "rtbo", "", ""),
            // P2 L24: 7c 2e, min 19 moves, dead 4.5% (seed 20115)
            listOf("gybt", "orpp", "rpbr", "brob", "optt", "yggg", "ytoy", "", ""),
            // P2 L25: 7c 2e, min 22 moves, dead 6.7% (seed 20120)
            listOf("ropo", "oprt", "ypyp", "rbbg", "ggyt", "ygtb", "rtbo", "", ""),
            // P2 L26: 7c 2e, min 21 moves, dead 6.2% (seed 20123)
            listOf("obor", "ypgy", "pytt", "obgr", "gbbr", "prpo", "yttg", "", ""),
            // P2 L27: 7c 2e, min 21 moves, dead 7.9% (seed 20126)
            listOf("obry", "opyt", "torg", "bygg", "rppt", "ybor", "gbpt", "", ""),
            // P2 L28: 7c 2e, min 20 moves, dead 7.1% (seed 20128)
            listOf("pttr", "boyt", "ytpo", "pgyr", "borr", "ggbb", "gpoy", "", ""),
            // P2 L29: 7c 2e, min 23 moves, dead 7.4% (seed 20131)
            listOf("boyo", "tbrg", "topp", "ogpr", "yrgb", "trgy", "ytbp", "", ""),
            // P2 L30: 7c 2e, min 24 moves, dead 7.1% (seed 20141)
            listOf("grbt", "ygrt", "otgb", "gory", "pytp", "pbpr", "oyob", "", ""),
            // P2 L31: 7c 2e, min 23 moves, dead 9.0% (seed 20142)
            listOf("yrpr", "pytt", "pgby", "gbpo", "btor", "yobg", "grot", "", ""),
            // P2 L32: 7c 2e, min 23 moves, dead 9.9% (seed 20143)
            listOf("yror", "gtty", "ybgo", "btrp", "rgop", "poby", "gpbt", "", ""),
            // P2 L33: 7c 2e, min 20 moves, dead 7.3% (seed 20144)
            listOf("obtt", "rrgy", "bgoo", "brpy", "gbgr", "typo", "yptp", "", ""),
            // P2 L34: 7c 2e, min 22 moves, dead 7.2% (seed 20158)
            listOf("gtyr", "yopo", "ypyr", "grbb", "tgtt", "bpog", "borp", "", ""),
            // P2 L35: 7c 2e, min 21 moves, dead 8.2% (seed 20168)
            listOf("poor", "yorp", "bypt", "tbtg", "yrtb", "bygg", "rpgo", "", ""),
            // P2 L36: 7c 2e, min 20 moves, dead 7.4% (seed 20170)
            listOf("rptg", "ygyr", "otgr", "oppo", "btop", "tryg", "bbby", "", ""),
            // P2 L37: 7c 2e, min 20 moves, dead 7.4% (seed 20172)
            listOf("grrp", "ytob", "ptyg", "gbpt", "yybb", "gtro", "roop", "", ""),
            // P2 L38: 7c 2e, min 21 moves, dead 9.0% (seed 20176)
            listOf("btty", "yprg", "borr", "bpoo", "bypy", "tgog", "prtg", "", ""),
            // P2 L39: 7c 2e, min 21 moves, dead 9.5% (seed 20177)
            listOf("rrog", "tpog", "bbop", "rybt", "pgyt", "gtry", "obyp", "", ""),
            // P2 L40: 7c 2e, min 19 moves, dead 8.2% (seed 20181)
            listOf("ytpg", "trbb", "yoot", "ygyg", "bprb", "rroo", "ppgt", "", ""),
        ),
        // Pack 3 - Easy 2
        listOf(
            // P3 L1: 7c 2e, min 21 moves, dead 7.7% (seed 30007)
            listOf("byyr", "ortr", "rbpy", "bgty", "ottg", "gbpp", "opgo", "", ""),
            // P3 L2: 7c 2e, min 23 moves, dead 6.2% (seed 30015)
            listOf("bgop", "prbt", "ytbt", "gygr", "oryr", "popt", "goby", "", ""),
            // P3 L3: 7c 2e, min 19 moves, dead 6.4% (seed 30016)
            listOf("rbgo", "ggpt", "ytoy", "pott", "rrog", "bryb", "bppy", "", ""),
            // P3 L4: 7c 2e, min 23 moves, dead 7.4% (seed 30019)
            listOf("gotr", "oyby", "popb", "otpg", "trgr", "gybp", "ytrb", "", ""),
            // P3 L5: 7c 2e, min 22 moves, dead 8.3% (seed 30027)
            listOf("brpt", "yypr", "ogbo", "gyrb", "otbp", "gotp", "rgty", "", ""),
            // P3 L6: 7c 2e, min 23 moves, dead 8.2% (seed 30036)
            listOf("yogo", "optr", "pbbr", "gtpb", "pgby", "rtgr", "yoty", "", ""),
            // P3 L7: 7c 2e, min 21 moves, dead 8.5% (seed 30057)
            listOf("rtry", "gbto", "rort", "pytb", "pogo", "gbbg", "yypp", "", ""),
            // P3 L8: 7c 2e, min 23 moves, dead 6.6% (seed 30058)
            listOf("ybtr", "rgog", "oyoy", "rotp", "grpb", "ybtp", "bptg", "", ""),
            // P3 L9: 7c 2e, min 23 moves, dead 7.8% (seed 30069)
            listOf("trtg", "bopt", "obgp", "rrpt", "ogby", "rgyy", "boyp", "", ""),
            // P3 L10: 7c 2e, min 20 moves, dead 7.3% (seed 30070)
            listOf("gtbr", "rtoy", "btrp", "ggby", "ogpp", "ryyt", "bpoo", "", ""),
            // P3 L11: 7c 2e, min 20 moves, dead 9.0% (seed 30076)
            listOf("ptgo", "otbg", "yoyt", "pbpy", "trro", "rryp", "gbbg", "", ""),
            // P3 L12: 7c 2e, min 23 moves, dead 8.3% (seed 30081)
            listOf("goor", "pobg", "gtpr", "tbrp", "ytbr", "ybyp", "ygot", "", ""),
            // P3 L13: 7c 2e, min 19 moves, dead 10.0% (seed 30096)
            listOf("ttto", "pory", "rrpb", "otbg", "yypo", "gbyb", "grpg", "", ""),
            // P3 L14: 7c 2e, min 20 moves, dead 8.3% (seed 30102)
            listOf("ottr", "poyt", "btbg", "pgyb", "gryy", "brpp", "groo", "", ""),
            // P3 L15: 7c 2e, min 20 moves, dead 9.0% (seed 30103)
            listOf("opty", "bpyt", "rrtt", "brgb", "bgyg", "oorg", "ppoy", "", ""),
            // P3 L16: 7c 2e, min 21 moves, dead 8.7% (seed 30104)
            listOf("rgot", "pbro", "yypo", "ybor", "rgyp", "ttpb", "gtgb", "", ""),
            // P3 L17: 7c 2e, min 22 moves, dead 8.0% (seed 30106)
            listOf("tgyr", "tpgb", "rpyt", "gooy", "bpoy", "pgtb", "borr", "", ""),
            // P3 L18: 7c 2e, min 19 moves, dead 11.0% (seed 30113)
            listOf("gtrr", "optt", "oogb", "bgto", "rgpy", "ybby", "yppr", "", ""),
            // P3 L19: 7c 2e, min 19 moves, dead 8.2% (seed 30115)
            listOf("rpgp", "royg", "ppyt", "ttyg", "bbob", "grty", "rboo", "", ""),
            // P3 L20: 7c 2e, min 24 moves, dead 8.2% (seed 30118)
            listOf("gpot", "tbyr", "ygtg", "pogb", "toyr", "pybp", "rbro", "", ""),
            // P3 L21: 7c 2e, min 22 moves, dead 11.3% (seed 30123)
            listOf("gopb", "toty", "ttyp", "rbyo", "bpgo", "ggpr", "rbyr", "", ""),
            // P3 L22: 7c 2e, min 22 moves, dead 11.3% (seed 30126)
            listOf("otrt", "gryb", "btbo", "gtpy", "poyg", "gybo", "rppr", "", ""),
            // P3 L23: 7c 2e, min 21 moves, dead 10.3% (seed 30127)
            listOf("rptp", "yrrt", "ogbg", "tgot", "ooyp", "prby", "bybg", "", ""),
            // P3 L24: 7c 2e, min 21 moves, dead 10.4% (seed 30136)
            listOf("ptoy", "gbop", "yrgr", "totp", "rrbb", "ygto", "ypbg", "", ""),
            // P3 L25: 7c 2e, min 22 moves, dead 10.1% (seed 30137)
            listOf("ybgp", "botg", "toby", "tpry", "bppt", "rogr", "ogyr", "", ""),
            // P3 L26: 7c 2e, min 24 moves, dead 10.0% (seed 30138)
            listOf("pyot", "gbrb", "gboy", "ptpo", "prty", "gtbg", "rroy", "", ""),
            // P3 L27: 7c 2e, min 23 moves, dead 12.3% (seed 30150)
            listOf("btry", "rgyr", "pobt", "royp", "otob", "pygg", "bpgt", "", ""),
            // P3 L28: 7c 2e, min 21 moves, dead 12.1% (seed 30155)
            listOf("yypg", "tpyr", "rptp", "borr", "tbot", "goob", "gybg", "", ""),
            // P3 L29: 7c 2e, min 22 moves, dead 11.0% (seed 30163)
            listOf("rbrb", "ptbo", "pgpg", "topr", "gyyt", "booy", "tgyr", "", ""),
            // P3 L30: 7c 2e, min 23 moves, dead 11.0% (seed 30190)
            listOf("ptpg", "yror", "ttbr", "gtob", "gpyo", "yryb", "gbop", "", ""),
            // P3 L31: 7c 2e, min 21 moves, dead 11.3% (seed 30192)
            listOf("bgot", "brpp", "ytgo", "rbpr", "gryt", "pbyy", "togo", "", ""),
            // P3 L32: 7c 2e, min 20 moves, dead 11.8% (seed 30207)
            listOf("pypb", "ogyy", "oopt", "yrrt", "brpg", "orgt", "bbgt", "", ""),
            // P3 L33: 7c 2e, min 22 moves, dead 11.5% (seed 30220)
            listOf("rtpo", "ytyt", "ogob", "ryby", "gbbr", "gopg", "rppt", "", ""),
            // P3 L34: 7c 2e, min 21 moves, dead 14.0% (seed 30233)
            listOf("rotg", "broo", "ybgt", "opyb", "trgp", "rgpt", "bpyy", "", ""),
            // P3 L35: 7c 2e, min 23 moves, dead 11.4% (seed 30245)
            listOf("ppbo", "togy", "obtr", "tgpb", "yrgr", "yrto", "ybgp", "", ""),
            // P3 L36: 7c 2e, min 22 moves, dead 13.2% (seed 30254)
            listOf("yogy", "bgby", "prry", "pptg", "ottg", "btro", "pobr", "", ""),
            // P3 L37: 7c 2e, min 22 moves, dead 13.4% (seed 30255)
            listOf("rppp", "boro", "btgt", "rgob", "ytpt", "ybog", "gyry", "", ""),
            // P3 L38: 7c 2e, min 20 moves, dead 12.0% (seed 30263)
            listOf("yrgo", "bttb", "yybg", "otot", "rgbp", "rrpp", "gpyo", "", ""),
            // P3 L39: 7c 2e, min 20 moves, dead 13.0% (seed 30285)
            listOf("rptt", "ttpb", "brgy", "yybp", "rgor", "yogp", "ogob", "", ""),
            // P3 L40: 7c 2e, min 21 moves, dead 13.3% (seed 30305)
            listOf("oror", "yttr", "tbbg", "grpo", "pyby", "gppt", "ybog", "", ""),
        ),
        // Pack 4 - Intermediate 1
        listOf(
            // P4 L1: 8c 2e, min 23 moves, dead 10.0% (seed 40010)
            listOf("ttyr", "rpog", "topb", "pyyt", "rgyp", "bbkk", "gork", "bkog", "", ""),
            // P4 L2: 8c 2e, min 24 moves, dead 8.1% (seed 40012)
            listOf("bgto", "yrpg", "poby", "kkbr", "rggp", "kbkr", "otyo", "yttp", "", ""),
            // P4 L3: 8c 2e, min 25 moves, dead 8.1% (seed 40016)
            listOf("kytr", "btyp", "ybgt", "ktpo", "yokg", "kgbb", "roor", "gprp", "", ""),
            // P4 L4: 8c 2e, min 25 moves, dead 9.4% (seed 40017)
            listOf("btrp", "gkyp", "gkkr", "koty", "bytr", "ybgg", "optp", "boro", "", ""),
            // P4 L5: 8c 2e, min 24 moves, dead 10.2% (seed 40018)
            listOf("ggtk", "ygbr", "oprt", "pptg", "toyr", "oykp", "brko", "bbyk", "", ""),
            // P4 L6: 8c 2e, min 26 moves, dead 9.0% (seed 40020)
            listOf("krto", "bpgk", "rykp", "rpgy", "ygor", "bkby", "tbtt", "gopo", "", ""),
            // P4 L7: 8c 2e, min 26 moves, dead 10.0% (seed 40022)
            listOf("ygoy", "ropt", "tptp", "bkpr", "bykg", "ytko", "bbgr", "korg", "", ""),
            // P4 L8: 8c 2e, min 25 moves, dead 10.7% (seed 40026)
            listOf("bpro", "rpbb", "pgry", "ytpo", "ogkg", "gbko", "ktkt", "yryt", "", ""),
            // P4 L9: 8c 2e, min 24 moves, dead 10.9% (seed 40036)
            listOf("ryog", "bykp", "kbpo", "tyrp", "prrk", "otog", "bbtg", "kgty", "", ""),
            // P4 L10: 8c 2e, min 25 moves, dead 9.9% (seed 40037)
            listOf("bork", "pypo", "gkpg", "ptgr", "bybb", "tkrr", "ytog", "tyok", "", ""),
            // P4 L11: 8c 2e, min 23 moves, dead 11.1% (seed 40039)
            listOf("optg", "oogb", "ttyk", "grgy", "rbky", "kkrt", "rbop", "ypbp", "", ""),
            // P4 L12: 8c 2e, min 27 moves, dead 12.8% (seed 40040)
            listOf("krtb", "okgr", "pgot", "pkbt", "tyob", "pygo", "gpry", "byrk", "", ""),
            // P4 L13: 8c 2e, min 26 moves, dead 11.5% (seed 40057)
            listOf("gyty", "bogk", "orrt", "kbpb", "pgro", "pttr", "ypoy", "kbgk", "", ""),
            // P4 L14: 8c 2e, min 25 moves, dead 10.4% (seed 40059)
            listOf("grtr", "gryo", "opkt", "gtkg", "bkpy", "obbk", "tbyy", "prop", "", ""),
            // P4 L15: 8c 2e, min 25 moves, dead 10.8% (seed 40060)
            listOf("yygk", "kgor", "rkpb", "bgkp", "prto", "oybp", "rgty", "tbot", "", ""),
            // P4 L16: 8c 2e, min 25 moves, dead 12.4% (seed 40062)
            listOf("ogbb", "broy", "ttpr", "pkrp", "koyg", "kgyr", "tgoy", "tkpb", "", ""),
            // P4 L17: 8c 2e, min 26 moves, dead 12.2% (seed 40063)
            listOf("gtgr", "rtty", "tyob", "gkyk", "rbrk", "bgop", "pkbp", "poyo", "", ""),
            // P4 L18: 8c 2e, min 27 moves, dead 10.1% (seed 40067)
            listOf("gbrg", "ybrp", "kyto", "tbkt", "ptgo", "koyp", "obrp", "rykg", "", ""),
            // P4 L19: 8c 2e, min 24 moves, dead 11.4% (seed 40071)
            listOf("krgt", "oprg", "yrkb", "tppy", "bytk", "ggto", "obop", "rybk", "", ""),
            // P4 L20: 8c 2e, min 26 moves, dead 11.5% (seed 40074)
            listOf("bgto", "pooy", "kykp", "rgtr", "yrgt", "pyrb", "otbk", "pbgk", "", ""),
            // P4 L21: 8c 2e, min 27 moves, dead 14.5% (seed 40076)
            listOf("orpk", "bgyo", "kpbp", "rpro", "gybt", "tygt", "rokb", "kgty", "", ""),
            // P4 L22: 8c 2e, min 27 moves, dead 12.4% (seed 40087)
            listOf("ybkb", "grbo", "toto", "kgop", "gkpt", "tgyp", "rpyr", "rkby", "", ""),
            // P4 L23: 8c 2e, min 24 moves, dead 12.6% (seed 40125)
            listOf("rrko", "obyb", "gbyk", "prtt", "ybrg", "ogpp", "ptko", "ytgk", "", ""),
            // P4 L24: 8c 2e, min 24 moves, dead 13.6% (seed 40143)
            listOf("byok", "pgog", "tgot", "orrp", "bbgy", "rrkt", "btyp", "kypk", "", ""),
            // P4 L25: 8c 2e, min 25 moves, dead 12.5% (seed 40152)
            listOf("krty", "gyby", "pogo", "rrbp", "btbk", "opyg", "gtpr", "kkto", "", ""),
            // P4 L26: 8c 2e, min 25 moves, dead 13.3% (seed 40173)
            listOf("kypt", "byko", "tttb", "ogkg", "yprk", "bprg", "oryp", "borg", "", ""),
            // P4 L27: 8c 2e, min 26 moves, dead 13.6% (seed 40175)
            listOf("gypk", "tgog", "pgyo", "bopt", "tkkb", "rpky", "rorb", "tbry", "", ""),
            // P4 L28: 8c 2e, min 26 moves, dead 14.1% (seed 40176)
            listOf("gbpy", "tbpk", "opry", "tgoo", "togb", "kryt", "pgry", "krbk", "", ""),
            // P4 L29: 8c 2e, min 26 moves, dead 14.1% (seed 40194)
            listOf("tptk", "btgp", "yoyr", "kgyr", "kypr", "boko", "ptgb", "rgbo", "", ""),
            // P4 L30: 8c 2e, min 24 moves, dead 14.3% (seed 40199)
            listOf("rppk", "gpby", "tgrt", "tyrt", "ookr", "pygo", "bgyb", "kkbo", "", ""),
            // P4 L31: 8c 2e, min 27 moves, dead 15.2% (seed 40205)
            listOf("opgk", "obpy", "tgkg", "rrtr", "pybk", "rtpy", "tkob", "obgy", "", ""),
            // P4 L32: 8c 2e, min 24 moves, dead 14.6% (seed 40207)
            listOf("bkko", "yyyk", "btpg", "trty", "brtg", "prgk", "bpog", "opor", "", ""),
            // P4 L33: 8c 2e, min 25 moves, dead 15.9% (seed 40217)
            listOf("tbbo", "obyr", "pgyr", "otkt", "ktpp", "gykp", "rgyr", "okbg", "", ""),
            // P4 L34: 8c 2e, min 24 moves, dead 14.2% (seed 40218)
            listOf("rtpr", "gokp", "ygtr", "bgpb", "kkpy", "rkgt", "ooyt", "yobb", "", ""),
            // P4 L35: 8c 2e, min 27 moves, dead 13.7% (seed 40221)
            listOf("gyrk", "ogkb", "gyor", "bktr", "ppty", "pbgt", "oyob", "ptkr", "", ""),
            // P4 L36: 8c 2e, min 28 moves, dead 13.3% (seed 40222)
            listOf("kotb", "pgkb", "pygk", "tgpo", "trpb", "yrbg", "kory", "tyor", "", ""),
            // P4 L37: 8c 2e, min 24 moves, dead 14.8% (seed 40239)
            listOf("oork", "ykpb", "tbbp", "otgg", "rkyg", "trpk", "poyg", "rbyt", "", ""),
            // P4 L38: 8c 2e, min 24 moves, dead 13.8% (seed 40250)
            listOf("obpk", "brtk", "yobg", "grrp", "otty", "gpob", "krkg", "ptyy", "", ""),
            // P4 L39: 8c 2e, min 26 moves, dead 14.2% (seed 40253)
            listOf("bykp", "grop", "kyot", "brgt", "rgpr", "pytb", "toky", "gbko", "", ""),
            // P4 L40: 8c 2e, min 25 moves, dead 14.0% (seed 40257)
            listOf("tgyk", "rrpg", "kbgy", "kpry", "rpbo", "pogt", "byoo", "tbkt", "", ""),
        ),
        // Pack 5 - Intermediate 2
        listOf(
            // P5 L1: 8c 2e, min 24 moves, dead 14.9% (seed 50008)
            listOf("kkpb", "rtoy", "ggbg", "ytro", "koty", "rkyr", "pbbo", "pgtp", "", ""),
            // P5 L2: 8c 2e, min 26 moves, dead 16.2% (seed 50011)
            listOf("kpry", "kygy", "tobb", "krpk", "ogby", "ttpb", "oogr", "trpg", "", ""),
            // P5 L3: 8c 2e, min 24 moves, dead 14.6% (seed 50017)
            listOf("rrtt", "ykpg", "otpp", "bkto", "pgok", "kbry", "bgby", "rgoy", "", ""),
            // P5 L4: 8c 2e, min 24 moves, dead 14.9% (seed 50019)
            listOf("book", "kgor", "tytt", "rtpg", "ogky", "bypp", "rbgb", "kypr", "", ""),
            // P5 L5: 8c 2e, min 25 moves, dead 16.7% (seed 50021)
            listOf("kgrb", "tyoo", "kgor", "tpyy", "gbpk", "trgk", "pbpy", "bort", "", ""),
            // P5 L6: 8c 2e, min 26 moves, dead 15.6% (seed 50022)
            listOf("ktop", "tyyb", "kogb", "krpb", "ggpt", "ryor", "gtyp", "krbo", "", ""),
            // P5 L7: 8c 2e, min 26 moves, dead 15.4% (seed 50027)
            listOf("oypr", "kyty", "rgty", "bkgt", "bogp", "pkbg", "rpkb", "toro", "", ""),
            // P5 L8: 8c 2e, min 26 moves, dead 14.9% (seed 50036)
            listOf("ykbk", "typo", "brtr", "obgk", "kpgt", "orpg", "rybp", "ygot", "", ""),
            // P5 L9: 8c 2e, min 24 moves, dead 16.3% (seed 50044)
            listOf("brto", "oort", "ppgy", "bypb", "kgrt", "btko", "rgkg", "pyyk", "", ""),
            // P5 L10: 8c 2e, min 26 moves, dead 15.0% (seed 50049)
            listOf("ppyg", "gbor", "orbt", "ktgk", "poby", "tygb", "rkyt", "opkr", "", ""),
            // P5 L11: 9c 2e, min 31 moves, dead 15.3% (seed 50050)
            listOf("ltyo", "gpyt", "york", "otpr", "gbkl", "klbr", "rpgt", "lkbo", "gypb", "", ""),
            // P5 L12: 9c 2e, min 29 moves, dead 14.3% (seed 50064)
            listOf("gltk", "ygkb", "pytt", "yklo", "ppto", "gryl", "plrb", "rbok", "ogrb", "", ""),
            // P5 L13: 9c 2e, min 30 moves, dead 12.4% (seed 50065)
            listOf("kgro", "lypb", "oprt", "rkgo", "glpl", "kboy", "yptk", "ytlb", "grbt", "", ""),
            // P5 L14: 9c 2e, min 29 moves, dead 15.5% (seed 50067)
            listOf("bpbt", "bgkt", "yltp", "brko", "glrl", "rgro", "topo", "pkyl", "kgyy", "", ""),
            // P5 L15: 9c 2e, min 27 moves, dead 15.7% (seed 50071)
            listOf("opro", "lkkp", "gkgt", "ppry", "lbyt", "tllo", "ybkt", "rbbr", "gygo", "", ""),
            // P5 L16: 9c 2e, min 27 moves, dead 14.5% (seed 50073)
            listOf("bgtk", "obbl", "rtrk", "kbgy", "gpoy", "tprk", "lorl", "ygpp", "loyt", "", ""),
            // P5 L17: 9c 2e, min 28 moves, dead 15.2% (seed 50075)
            listOf("rblb", "ogpk", "ttyl", "tkgp", "lgyp", "kypr", "olkt", "rbbr", "yogo", "", ""),
            // P5 L18: 9c 2e, min 27 moves, dead 14.4% (seed 50076)
            listOf("pgkt", "kpgl", "tkot", "rrlo", "gbll", "ryyt", "opgb", "pbyr", "byko", "", ""),
            // P5 L19: 9c 2e, min 29 moves, dead 13.6% (seed 50088)
            listOf("klpr", "brpt", "bkyy", "rpyl", "btgl", "tbgr", "kggy", "opot", "oklo", "", ""),
            // P5 L20: 9c 2e, min 29 moves, dead 12.0% (seed 50094)
            listOf("lrgp", "lppo", "rbyt", "pktk", "lbtg", "bgko", "lbot", "yyry", "rkgo", "", ""),
            // P5 L21: 9c 2e, min 26 moves, dead 16.3% (seed 50103)
            listOf("kgob", "ppbg", "blty", "plgr", "lkyo", "prkr", "ttyt", "roog", "ybkl", "", ""),
            // P5 L22: 9c 2e, min 28 moves, dead 17.3% (seed 50106)
            listOf("plpo", "gbyl", "tkok", "kpkl", "yyby", "grpr", "orgg", "otbr", "tlbt", "", ""),
            // P5 L23: 9c 2e, min 27 moves, dead 15.5% (seed 50110)
            listOf("glgt", "klty", "lbrk", "yykp", "pgok", "bbrp", "rrgy", "btlo", "opot", "", ""),
            // P5 L24: 9c 2e, min 27 moves, dead 16.1% (seed 50116)
            listOf("yygk", "rott", "yobk", "llpo", "rprl", "pgpb", "rykg", "bgol", "ktbt", "", ""),
            // P5 L25: 9c 2e, min 28 moves, dead 17.7% (seed 50132)
            listOf("okkl", "gybg", "lpkr", "typp", "lgbt", "rloy", "btor", "grbp", "otky", "", ""),
            // P5 L26: 9c 2e, min 29 moves, dead 17.5% (seed 50133)
            listOf("pgbt", "pkyo", "blgp", "gkkr", "typy", "lblr", "olkr", "tgbt", "oyro", "", ""),
            // P5 L27: 9c 2e, min 27 moves, dead 17.0% (seed 50139)
            listOf("lrpl", "rpog", "oybo", "ttok", "kkyl", "pbgy", "ybpt", "rbtl", "rkgg", "", ""),
            // P5 L28: 9c 2e, min 28 moves, dead 17.4% (seed 50142)
            listOf("yrkr", "ylpo", "bbkl", "ktpg", "ptgr", "tkyy", "pbrl", "goto", "gbol", "", ""),
            // P5 L29: 9c 2e, min 29 moves, dead 15.8% (seed 50152)
            listOf("rpbp", "kkto", "boyb", "yprl", "gkyg", "rtol", "gkgb", "lytp", "lrto", "", ""),
            // P5 L30: 9c 2e, min 28 moves, dead 16.4% (seed 50159)
            listOf("kytb", "krlg", "obol", "pppr", "ygyr", "pobl", "kgbg", "ltry", "tkto", "", ""),
            // P5 L31: 9c 2e, min 28 moves, dead 17.1% (seed 50166)
            listOf("bgyt", "rrop", "btyr", "kool", "plpg", "tkob", "grkt", "kllg", "ybpy", "", ""),
            // P5 L32: 9c 2e, min 29 moves, dead 19.1% (seed 50176)
            listOf("okyr", "kgrb", "bgtp", "ypbk", "ttrl", "yrpy", "bplg", "olgl", "ookt", "", ""),
            // P5 L33: 9c 2e, min 29 moves, dead 19.8% (seed 50183)
            listOf("kytb", "rgpy", "gpog", "oolr", "lkgt", "kltr", "ybpb", "rplt", "obyk", "", ""),
            // P5 L34: 9c 2e, min 29 moves, dead 18.5% (seed 50199)
            listOf("lpot", "klbg", "lkpo", "bytk", "oyor", "bygr", "kgbp", "ttrl", "grpy", "", ""),
            // P5 L35: 9c 2e, min 27 moves, dead 17.1% (seed 50201)
            listOf("rkkl", "boty", "lkbp", "gpto", "glpb", "pyrk", "rgyl", "ooyr", "gbtt", "", ""),
            // P5 L36: 9c 2e, min 30 moves, dead 19.1% (seed 50204)
            listOf("ltgb", "bokp", "yror", "pkgk", "pytl", "oorl", "pbtr", "tgkl", "ybyg", "", ""),
            // P5 L37: 9c 2e, min 30 moves, dead 19.0% (seed 50211)
            listOf("tlyk", "bkgo", "lbpy", "lpoo", "bryt", "grpg", "krpl", "krob", "tygt", "", ""),
            // P5 L38: 9c 2e, min 31 moves, dead 19.3% (seed 50221)
            listOf("kltr", "lolp", "ybkg", "tbrb", "ogpg", "tgpr", "kylk", "opry", "obyt", "", ""),
            // P5 L39: 9c 2e, min 29 moves, dead 19.0% (seed 50225)
            listOf("ktyo", "ptop", "tkrg", "gbyl", "bboy", "kgog", "plrr", "klby", "tlrp", "", ""),
            // P5 L40: 9c 2e, min 27 moves, dead 19.0% (seed 50228)
            listOf("kbry", "byll", "lobg", "ykrg", "gopp", "togk", "pytt", "oktr", "bplr", "", ""),
        ),
        // Pack 6 - Hard 1
        listOf(
            // P6 L1: 9c 2e, min 27 moves, dead 17.4% (seed 60016)
            listOf("pogr", "opol", "kytg", "bkgt", "grbb", "tplr", "lrly", "tokk", "ypby", "", ""),
            // P6 L2: 9c 2e, min 28 moves, dead 19.7% (seed 60027)
            listOf("ogob", "brgp", "ryrt", "ggtk", "lklp", "plot", "kbky", "plor", "byty", "", ""),
            // P6 L3: 9c 2e, min 28 moves, dead 17.7% (seed 60034)
            listOf("rggy", "gtkb", "porp", "ploy", "lbrb", "kltp", "yttl", "rkbk", "gooy", "", ""),
            // P6 L4: 9c 2e, min 27 moves, dead 17.3% (seed 60035)
            listOf("gbbl", "kryy", "kogp", "ttyy", "grpo", "kopt", "lrrl", "kpob", "tglb", "", ""),
            // P6 L5: 9c 2e, min 26 moves, dead 17.9% (seed 60041)
            listOf("kltt", "okbp", "oktr", "bpky", "btyr", "oogl", "ppry", "gygr", "llbg", "", ""),
            // P6 L6: 9c 2e, min 28 moves, dead 18.1% (seed 60048)
            listOf("royg", "ykll", "ggtr", "robl", "ykbo", "tkbp", "ptyl", "brto", "pkpg", "", ""),
            // P6 L7: 9c 2e, min 28 moves, dead 18.6% (seed 60049)
            listOf("yrbk", "lltp", "brog", "kblr", "oggt", "ytpt", "kbry", "goly", "popk", "", ""),
            // P6 L8: 9c 2e, min 28 moves, dead 19.9% (seed 60051)
            listOf("bryb", "pryl", "oogk", "yltg", "ptkr", "plpy", "gobt", "korl", "tgkb", "", ""),
            // P6 L9: 9c 2e, min 28 moves, dead 19.9% (seed 60052)
            listOf("krol", "porl", "ggtb", "btbp", "ygyo", "yllr", "ptkk", "pgyo", "kbtr", "", ""),
            // P6 L10: 9c 2e, min 29 moves, dead 17.7% (seed 60071)
            listOf("opgk", "blbo", "kgko", "yrbg", "rllk", "ylrp", "tgpp", "otyt", "rbyt", "", ""),
            // P6 L11: 9c 2e, min 30 moves, dead 20.0% (seed 60075)
            listOf("kryl", "koyk", "gbbo", "lrlp", "ogrk", "tglr", "bgpb", "poyt", "tpyt", "", ""),
            // P6 L12: 9c 2e, min 31 moves, dead 21.8% (seed 60078)
            listOf("bkgp", "lrtl", "botp", "yybp", "gtor", "lyol", "ktgk", "kyrb", "pgor", "", ""),
            // P6 L13: 9c 2e, min 29 moves, dead 19.8% (seed 60086)
            listOf("pbpr", "topr", "gbgy", "goty", "pbkl", "rgol", "lkko", "lbrt", "kyty", "", ""),
            // P6 L14: 9c 2e, min 28 moves, dead 21.2% (seed 60090)
            listOf("gtkp", "bpkk", "rloy", "yory", "gbgl", "ytgl", "bbkr", "otlt", "rppo", "", ""),
            // P6 L15: 9c 2e, min 29 moves, dead 19.9% (seed 60094)
            listOf("typt", "rybl", "brly", "olkb", "ogtg", "obpr", "prkk", "lygk", "ogtp", "", ""),
            // P6 L16: 9c 2e, min 31 moves, dead 22.0% (seed 60098)
            listOf("tkok", "yplr", "btpy", "btlr", "pygl", "ogkr", "blpg", "rkgb", "oyto", "", ""),
            // P6 L17: 9c 2e, min 27 moves, dead 20.9% (seed 60119)
            listOf("ygkp", "ogtk", "rrtb", "oopy", "plkl", "ybrr", "lgkt", "bltp", "ygob", "", ""),
            // P6 L18: 9c 2e, min 28 moves, dead 19.6% (seed 60131)
            listOf("rtog", "bgoy", "byyk", "kgkb", "rlky", "bltp", "rolg", "lppp", "trot", "", ""),
            // P6 L19: 9c 2e, min 29 moves, dead 19.6% (seed 60142)
            listOf("tggp", "tkro", "tpro", "plpy", "yrbl", "ykbb", "loko", "grbk", "ytgl", "", ""),
            // P6 L20: 9c 2e, min 27 moves, dead 20.7% (seed 60165)
            listOf("ypoo", "typk", "lgtb", "gbyl", "oplr", "brrt", "pkyg", "brgt", "lkko", "", ""),
            // P6 L21: 9c 2e, min 27 moves, dead 21.8% (seed 60168)
            listOf("ygrr", "otbb", "togp", "prbl", "lrlo", "plkk", "ykto", "yygp", "tgbk", "", ""),
            // P6 L22: 9c 2e, min 30 moves, dead 21.4% (seed 60171)
            listOf("polk", "blrg", "krgk", "pryt", "gytb", "pllb", "roto", "yptg", "kybo", "", ""),
            // P6 L23: 9c 2e, min 29 moves, dead 22.1% (seed 60183)
            listOf("kbyo", "gror", "ybop", "gltp", "kylg", "kkpt", "tybg", "blpr", "orlt", "", ""),
            // P6 L24: 9c 2e, min 28 moves, dead 21.7% (seed 60200)
            listOf("ptpp", "rkrb", "kobt", "kygy", "ylly", "prgk", "btlb", "glot", "roog", "", ""),
            // P6 L25: 9c 2e, min 29 moves, dead 22.1% (seed 60201)
            listOf("rooy", "botl", "rgpl", "gykk", "blrk", "pgby", "rtgb", "tkyp", "ptlo", "", ""),
            // P6 L26: 9c 2e, min 29 moves, dead 23.8% (seed 60212)
            listOf("lbpg", "ogbk", "rpkt", "olkb", "ttyb", "tkyo", "gylr", "oglp", "yrpr", "", ""),
            // P6 L27: 9c 2e, min 30 moves, dead 22.2% (seed 60222)
            listOf("gpot", "ryyb", "tygb", "kblt", "grlk", "ktrl", "lpyr", "kpgo", "opob", "", ""),
            // P6 L28: 9c 2e, min 29 moves, dead 23.7% (seed 60227)
            listOf("kpkg", "kbyp", "plyt", "rrot", "gylb", "rrbo", "opyl", "kgto", "gltb", "", ""),
            // P6 L29: 9c 2e, min 30 moves, dead 22.7% (seed 60259)
            listOf("gpko", "lylt", "goyo", "kobg", "bypp", "rlbk", "rlrt", "ktby", "rtgp", "", ""),
            // P6 L30: 9c 2e, min 28 moves, dead 21.8% (seed 60260)
            listOf("kpyo", "gkol", "ytrt", "gkrt", "prbg", "ygtr", "obbp", "yblp", "llko", "", ""),
            // P6 L31: 9c 2e, min 28 moves, dead 25.8% (seed 60264)
            listOf("glbt", "pbot", "ktby", "bogk", "koly", "gtpp", "kyor", "lrrp", "rlyg", "", ""),
            // P6 L32: 9c 2e, min 31 moves, dead 24.2% (seed 60275)
            listOf("btkp", "gpyk", "yorp", "ktbl", "glog", "otlb", "yrtr", "glro", "kypb", "", ""),
            // P6 L33: 9c 2e, min 27 moves, dead 24.0% (seed 60284)
            listOf("gtpk", "tott", "lybg", "gryy", "pylk", "oork", "orpr", "pbbk", "lblg", "", ""),
            // P6 L34: 9c 2e, min 29 moves, dead 25.1% (seed 60312)
            listOf("brgk", "lrby", "byoo", "rptk", "tgby", "yotg", "kpol", "ptlr", "kplg", "", ""),
            // P6 L35: 9c 2e, min 27 moves, dead 25.4% (seed 60313)
            listOf("rbol", "ppyb", "tgyb", "tror", "gtpl", "okol", "lkkb", "ptkg", "gryy", "", ""),
            // P6 L36: 9c 2e, min 30 moves, dead 25.5% (seed 60327)
            listOf("llyr", "tbkp", "prko", "tprg", "yprb", "gybk", "ltko", "logt", "gbyo", "", ""),
            // P6 L37: 9c 2e, min 29 moves, dead 25.3% (seed 60365)
            listOf("lkpr", "tgrt", "rgyo", "yypk", "bpbl", "loto", "lprb", "ktgy", "kobg", "", ""),
            // P6 L38: 9c 2e, min 28 moves, dead 26.0% (seed 60395)
            listOf("ppky", "kyyt", "rolt", "krto", "blkl", "gobo", "grbl", "tbgp", "gpyr", "", ""),
            // P6 L39: 9c 2e, min 30 moves, dead 25.9% (seed 60448)
            listOf("orkp", "ptlt", "gbyg", "gorp", "yrpy", "kobo", "gtrl", "ltkb", "bykl", "", ""),
            // P6 L40: 9c 2e, min 27 moves, dead 24.5% (seed 60458)
            listOf("plro", "ybkt", "glol", "obkk", "rglg", "ttpp", "pyby", "kbro", "ytrg", "", ""),
        ),
        // Pack 7 - Hard 2
        listOf(
            // P7 L1: 10c 2e, min 30 moves, dead 20.2% (seed 70009)
            listOf("gttt", "rlpk", "crlo", "clgg", "yobp", "rpkb", "yocg", "cytl", "bkkr", "poyb", "", ""),
            // P7 L2: 10c 2e, min 29 moves, dead 22.6% (seed 70012)
            listOf("tptk", "ppyy", "brct", "cggc", "pblc", "rblb", "lyoo", "ktog", "rglk", "okyr", "", ""),
            // P7 L3: 10c 2e, min 32 moves, dead 21.3% (seed 70018)
            listOf("kkrt", "obyc", "bctg", "rlpo", "ylpy", "lgcy", "pgrb", "kcgt", "rokl", "btop", "", ""),
            // P7 L4: 10c 2e, min 33 moves, dead 19.7% (seed 70021)
            listOf("klyo", "copk", "lrgp", "yrog", "cbgt", "rytp", "btkg", "pbtc", "lyrl", "kocb", "", ""),
            // P7 L5: 10c 2e, min 32 moves, dead 21.8% (seed 70030)
            listOf("tgot", "clyc", "kgok", "rgbp", "bpyl", "tkcp", "llog", "kcro", "ptry", "ybrb", "", ""),
            // P7 L6: 10c 2e, min 31 moves, dead 19.0% (seed 70043)
            listOf("yopp", "rrok", "bgyc", "otyc", "otrp", "bbtk", "krkb", "lgll", "tglp", "cygc", "", ""),
            // P7 L7: 10c 2e, min 33 moves, dead 22.1% (seed 70048)
            listOf("pkkb", "lgtb", "lrtc", "ogkb", "oort", "lrgc", "pyrc", "obyk", "ycgt", "yppl", "", ""),
            // P7 L8: 10c 2e, min 33 moves, dead 21.8% (seed 70064)
            listOf("crko", "oykr", "gbkc", "bpop", "bgck", "tltl", "ygpy", "lgtc", "rtor", "yblp", "", ""),
            // P7 L9: 10c 2e, min 32 moves, dead 21.5% (seed 70071)
            listOf("lcty", "obtt", "lobk", "pypr", "ycok", "tbrp", "ogkg", "rrgl", "pcyk", "lgcb", "", ""),
            // P7 L10: 10c 2e, min 30 moves, dead 22.3% (seed 70075)
            listOf("klbo", "pryl", "rpbc", "rrtp", "cgyy", "gotl", "ctgg", "lcby", "kkbo", "potk", "", ""),
            // P7 L11: 10c 2e, min 29 moves, dead 22.2% (seed 70078)
            listOf("locr", "tgll", "pbbb", "gcry", "gpyk", "gykr", "rtkc", "pttk", "ypoo", "lboc", "", ""),
            // P7 L12: 10c 2e, min 32 moves, dead 24.6% (seed 70087)
            listOf("golg", "kktk", "rkpl", "pycr", "bcpy", "rygc", "ttbo", "logp", "byob", "trcl", "", ""),
            // P7 L13: 10c 2e, min 29 moves, dead 24.4% (seed 70091)
            listOf("bkll", "rtkl", "ybco", "gyog", "bboc", "ltkk", "prct", "rpyy", "gppo", "crtg", "", ""),
            // P7 L14: 10c 2e, min 32 moves, dead 25.5% (seed 70092)
            listOf("olyg", "gbtb", "krog", "rtpp", "cokr", "plkt", "bykl", "gtcr", "poly", "cycb", "", ""),
            // P7 L15: 10c 2e, min 35 moves, dead 24.2% (seed 70101)
            listOf("bobk", "gktc", "tbpk", "yrog", "glto", "toyc", "rlpl", "ccyg", "bpkr", "yplr", "", ""),
            // P7 L16: 10c 2e, min 31 moves, dead 25.7% (seed 70107)
            listOf("lbtr", "lkyr", "rcct", "gygc", "oopo", "tbty", "gcbb", "yppo", "rklk", "pkgl", "", ""),
            // P7 L17: 10c 2e, min 32 moves, dead 25.2% (seed 70109)
            listOf("tytp", "rgop", "rooy", "kbtl", "rpkl", "lcpt", "gkcb", "ylgc", "rcyb", "ogbk", "", ""),
            // P7 L18: 10c 2e, min 32 moves, dead 24.2% (seed 70121)
            listOf("ypkc", "pccy", "rtob", "olcr", "pryk", "lokb", "lygt", "pbog", "ktgl", "bgrt", "", ""),
            // P7 L19: 10c 2e, min 33 moves, dead 23.3% (seed 70147)
            listOf("ycly", "pggo", "otrp", "trbl", "brky", "lokg", "btyo", "pcrc", "tgpc", "klbk", "", ""),
            // P7 L20: 10c 2e, min 30 moves, dead 22.7% (seed 70150)
            listOf("ccpp", "yybr", "ockg", "yglp", "ktrr", "bpol", "roct", "oltg", "kbyl", "ktgb", "", ""),
            // P7 L21: 10c 2e, min 33 moves, dead 24.9% (seed 70152)
            listOf("bgco", "kpcb", "obrp", "rttp", "glgy", "rklt", "yrpl", "ytgc", "boyk", "kocl", "", ""),
            // P7 L22: 10c 2e, min 31 moves, dead 25.9% (seed 70154)
            listOf("gbyl", "pylk", "tgcp", "btyp", "rllo", "ygrt", "pgco", "cokb", "rtoc", "rkkb", "", ""),
            // P7 L23: 10c 2e, min 30 moves, dead 26.1% (seed 70165)
            listOf("gypl", "llpk", "bbor", "tbry", "gctg", "rokk", "clop", "yopc", "tgyc", "kbrt", "", ""),
            // P7 L24: 10c 2e, min 32 moves, dead 24.9% (seed 70179)
            listOf("rpgy", "bbkc", "tcyr", "ptco", "oopg", "kylb", "kglo", "prkr", "bgty", "tlcl", "", ""),
            // P7 L25: 10c 2e, min 32 moves, dead 24.0% (seed 70184)
            listOf("lgtp", "tkoo", "cypl", "gybt", "lryt", "lgcc", "rogb", "kbcp", "kbkr", "rpyo", "", ""),
            // P7 L26: 10c 2e, min 32 moves, dead 25.2% (seed 70215)
            listOf("tcrl", "ypgo", "rgpc", "lrko", "bbtr", "gtck", "lgyk", "obcp", "ybot", "yklp", "", ""),
            // P7 L27: 10c 2e, min 34 moves, dead 27.2% (seed 70216)
            listOf("bygk", "ckcg", "klog", "bpyp", "ptrt", "ltrk", "opol", "ogrt", "lcby", "byrc", "", ""),
            // P7 L28: 10c 2e, min 30 moves, dead 24.9% (seed 70243)
            listOf("kolo", "tprt", "yyor", "rglt", "klro", "ccgc", "bbcp", "ypkb", "glpk", "bytg", "", ""),
            // P7 L29: 10c 2e, min 31 moves, dead 25.4% (seed 70254)
            listOf("blkc", "rggo", "topr", "ockb", "bkyg", "rlgt", "lprp", "ycpl", "ktob", "ctyy", "", ""),
            // P7 L30: 10c 2e, min 31 moves, dead 27.3% (seed 70265)
            listOf("blrg", "ggkk", "ocpt", "cyyo", "bork", "ytkl", "ctpc", "pgbr", "ylpo", "blrt", "", ""),
            // P7 L31: 10c 2e, min 32 moves, dead 26.4% (seed 70274)
            listOf("clpb", "ptol", "blkg", "yryc", "rkto", "trpt", "bolg", "ccoy", "rgkb", "kpyg", "", ""),
            // P7 L32: 10c 2e, min 31 moves, dead 26.6% (seed 70286)
            listOf("kbbo", "pllk", "kgto", "ctgr", "ryyt", "lrgt", "ykoy", "cpcp", "cbgb", "rpol", "", ""),
            // P7 L33: 10c 2e, min 33 moves, dead 27.9% (seed 70298)
            listOf("opcr", "lkbr", "lpgy", "grtr", "byot", "otck", "lkpp", "cobg", "tlyb", "gcyk", "", ""),
            // P7 L34: 10c 2e, min 31 moves, dead 28.9% (seed 70303)
            listOf("krpp", "ylyo", "kogg", "ckpt", "pytc", "ltgc", "rbct", "gllb", "rboy", "rbok", "", ""),
            // P7 L35: 10c 2e, min 31 moves, dead 26.8% (seed 70334)
            listOf("bopk", "cbcb", "ttol", "ckyp", "ybpy", "lrlk", "rkgg", "glty", "pror", "gtoc", "", ""),
            // P7 L36: 10c 2e, min 33 moves, dead 27.7% (seed 70370)
            listOf("kocl", "llob", "booy", "ptrg", "bcry", "kcpr", "ctrt", "pkgy", "ygpl", "kgbt", "", ""),
            // P7 L37: 10c 2e, min 30 moves, dead 26.3% (seed 70373)
            listOf("crpg", "bbct", "ygll", "cpto", "oytg", "ryok", "kllc", "ktgr", "kbbr", "opyp", "", ""),
            // P7 L38: 10c 2e, min 32 moves, dead 28.7% (seed 70377)
            listOf("gcly", "tpbk", "gply", "pgly", "korp", "ocrc", "yogc", "tbkk", "bbrt", "lotr", "", ""),
            // P7 L39: 10c 2e, min 34 moves, dead 27.5% (seed 70394)
            listOf("pctg", "pokc", "oyrt", "bgor", "klyp", "ryrc", "btkg", "btyl", "colg", "kplb", "", ""),
            // P7 L40: 10c 2e, min 32 moves, dead 26.2% (seed 70405)
            listOf("topr", "lgbt", "olkc", "brog", "pykr", "rcbt", "pplg", "oytl", "bgyc", "ykkc", "", ""),
        ),
        // Pack 8 - Hard 3
        listOf(
            // P8 L1: 10c 2e, min 32 moves, dead 25.5% (seed 80024)
            listOf("bgty", "kpro", "tokl", "rptl", "lrbc", "obkt", "yokg", "cygp", "lpyg", "rcbc", "", ""),
            // P8 L2: 10c 2e, min 31 moves, dead 26.7% (seed 80025)
            listOf("ygob", "gtby", "ccky", "orbt", "oppg", "lbot", "cyrk", "lrpl", "lptc", "kkrg", "", ""),
            // P8 L3: 10c 2e, min 34 moves, dead 24.6% (seed 80027)
            listOf("kgly", "plyg", "tlkb", "bkrc", "oyrc", "bkot", "ocpt", "otrg", "lrpy", "gpcb", "", ""),
            // P8 L4: 10c 2e, min 30 moves, dead 24.3% (seed 80031)
            listOf("ytkb", "oylt", "ccpr", "cgot", "ykob", "rggc", "kkpb", "obrl", "ltpy", "gprl", "", ""),
            // P8 L5: 10c 2e, min 32 moves, dead 25.6% (seed 80038)
            listOf("ltcb", "rogc", "toop", "tplg", "kbyl", "kkrp", "gtpr", "kbro", "ygcy", "clyb", "", ""),
            // P8 L6: 10c 2e, min 34 moves, dead 27.0% (seed 80040)
            listOf("bort", "plol", "cpkp", "tyyg", "bylk", "gygc", "bctr", "pokg", "okrb", "tcrl", "", ""),
            // P8 L7: 10c 2e, min 30 moves, dead 26.5% (seed 80045)
            listOf("ktly", "obtc", "plcl", "kbyy", "ggtg", "lyrp", "rkko", "pgob", "porc", "bcrt", "", ""),
            // P8 L8: 10c 2e, min 30 moves, dead 24.2% (seed 80076)
            listOf("rbbo", "yppy", "gtrg", "ogcr", "kctb", "lrlc", "kgpl", "ytyc", "tblp", "kook", "", ""),
            // P8 L9: 6c 1e, min 15 moves, dead 17.6% (seed 80156)
            listOf("yrgp", "bbor", "ypgg", "poby", "oopg", "rryb", ""),
            // P8 L10: 6c 1e, min 18 moves, dead 22.9% (seed 80208)
            listOf("popp", "yrpy", "rygr", "obgr", "ggbo", "boyb", ""),
            // P8 L11: 6c 1e, min 17 moves, dead 17.6% (seed 80240)
            listOf("ggor", "rbby", "gprp", "brpy", "oobg", "pyoy", ""),
            // P8 L12: 6c 1e, min 13 moves, dead 10.0% (seed 80281)
            listOf("yboy", "pyog", "rrrg", "gpyr", "oopp", "bbbg", ""),
            // P8 L13: 10c 2e, min 32 moves, dead 30.5% (seed 80301)
            listOf("clbr", "tbpr", "tgpp", "tkrt", "lkky", "poky", "oryg", "ogby", "clcb", "gocl", "", ""),
            // P8 L14: 10c 2e, min 32 moves, dead 27.8% (seed 80304)
            listOf("lrpt", "pryp", "bcpk", "klbb", "yorr", "octk", "gtlg", "yocb", "klcg", "ogty", "", ""),
            // P8 L15: 10c 2e, min 32 moves, dead 27.2% (seed 80329)
            listOf("ybtp", "lrlg", "lcto", "gokp", "rkgc", "gybk", "bcby", "pklr", "rytt", "pooc", "", ""),
            // P8 L16: 10c 2e, min 34 moves, dead 31.4% (seed 80331)
            listOf("ypol", "lotc", "kggo", "gbpr", "krpr", "ltpl", "cokt", "gcyy", "kbyb", "ctbr", "", ""),
            // P8 L17: 10c 2e, min 32 moves, dead 31.1% (seed 80335)
            listOf("glco", "llog", "kctg", "rkpr", "byby", "otrr", "ptkb", "cpoc", "pyyg", "ltkb", "", ""),
            // P8 L18: 10c 2e, min 33 moves, dead 28.9% (seed 80347)
            listOf("lytc", "ctgk", "pobr", "otlr", "plbp", "gyty", "bpkr", "roko", "kycl", "cgbg", "", ""),
            // P8 L19: 10c 2e, min 30 moves, dead 29.4% (seed 80354)
            listOf("lpko", "pkrg", "ycro", "trot", "cgtl", "bbkc", "bryy", "bgyl", "topp", "gklc", "", ""),
            // P8 L20: 10c 2e, min 31 moves, dead 29.9% (seed 80355)
            listOf("yrcb", "tygl", "rocl", "pgkt", "pkor", "lkty", "toog", "lcbb", "bpyg", "crpk", "", ""),
            // P8 L21: 10c 2e, min 30 moves, dead 28.0% (seed 80360)
            listOf("kppy", "cgtg", "ktlo", "ggyy", "lkbt", "ybto", "bkbp", "corc", "rorp", "llrc", "", ""),
            // P8 L22: 10c 2e, min 32 moves, dead 28.4% (seed 80364)
            listOf("btlc", "ykkp", "ygyt", "tylg", "krcr", "cpkp", "ocob", "pgtb", "lrog", "brlo", "", ""),
            // P8 L23: 6c 1e, min 16 moves, dead 26.3% (seed 80399)
            listOf("gygr", "ryyr", "rpbo", "yggp", "pboo", "bobp", ""),
            // P8 L24: 6c 1e, min 16 moves, dead 22.1% (seed 80454)
            listOf("pbpr", "oooy", "rgbg", "rrgg", "pypb", "ybyo", ""),
            // P8 L25: 6c 1e, min 19 moves, dead 24.2% (seed 80531)
            listOf("obyo", "ggyr", "bpyb", "rbro", "pryo", "pgpg", ""),
            // P8 L26: 6c 1e, min 15 moves, dead 29.5% (seed 80549)
            listOf("ggbg", "oobp", "gror", "byyb", "yyop", "rprp", ""),
            // P8 L27: 10c 2e, min 31 moves, dead 30.5% (seed 80566)
            listOf("koty", "clkr", "kctr", "tpbb", "ryyp", "cbyg", "lotl", "pglo", "grok", "pbgc", "", ""),
            // P8 L28: 10c 2e, min 30 moves, dead 33.9% (seed 80593)
            listOf("tkyb", "ccbl", "clgb", "yllk", "rtor", "kyot", "ogpt", "ggby", "kpcr", "ropp", "", ""),
            // P8 L29: 10c 2e, min 34 moves, dead 34.5% (seed 80596)
            listOf("rbgy", "btpr", "clyg", "ctlc", "rpyp", "kotr", "obck", "ootp", "kgyl", "bglk", "", ""),
            // P8 L30: 10c 2e, min 31 moves, dead 34.9% (seed 80600)
            listOf("pobk", "lgko", "tckg", "ttbr", "tpgy", "bpol", "lgko", "crcl", "cpyy", "rryb", "", ""),
            // P8 L31: 10c 2e, min 31 moves, dead 30.6% (seed 80617)
            listOf("ckbt", "lopg", "rptg", "bloo", "rlrg", "cpbt", "rktb", "lyyk", "opyy", "ccgk", "", ""),
            // P8 L32: 10c 2e, min 32 moves, dead 30.7% (seed 80620)
            listOf("obor", "grck", "pglt", "oobt", "ctct", "klpg", "bcpy", "kyyr", "kygl", "brlp", "", ""),
            // P8 L33: 10c 2e, min 32 moves, dead 32.0% (seed 80625)
            listOf("tylp", "rogy", "pybt", "kkbp", "lcor", "prgl", "okyg", "obtc", "ckrb", "tclg", "", ""),
            // P8 L34: 10c 2e, min 33 moves, dead 33.1% (seed 80629)
            listOf("lccr", "rpyl", "gkog", "pktp", "lcpt", "brcy", "olko", "ryyg", "gbtk", "btbo", "", ""),
            // P8 L35: 10c 2e, min 33 moves, dead 30.5% (seed 80668)
            listOf("ccgk", "lkgt", "kcrp", "kplb", "rlor", "toyt", "tybo", "rgpo", "ylpy", "cbgb", "", ""),
            // P8 L36: 10c 2e, min 34 moves, dead 30.4% (seed 80670)
            listOf("yltk", "tgot", "grob", "pyco", "lcyc", "rorp", "bckl", "lkrb", "pybt", "gpkg", "", ""),
            // P8 L37: 7c 1e, min 21 moves, dead 29.1% (seed 80839)
            listOf("rpto", "brpy", "pyoo", "gtbg", "tggr", "bybo", "rtyp", ""),
            // P8 L38: 7c 1e, min 23 moves, dead 25.4% (seed 81056)
            listOf("porb", "gygp", "robg", "tyty", "ygtb", "rbpt", "opor", ""),
            // P8 L39: 7c 1e, min 18 moves, dead 29.0% (seed 81170)
            listOf("ggoy", "bbrt", "ygtt", "gypt", "rryp", "oopr", "bbop", ""),
            // P8 L40: 7c 1e, min 20 moves, dead 26.5% (seed 81497)
            listOf("ppyg", "ytrb", "rpbt", "oogr", "tgtp", "oogb", "yryb", ""),
        ),
        // Pack 9 - Extreme 1
        listOf(
            // P9 L1: 12c 2e, min 39 moves, dead 27.7% (seed 90006)
            listOf("vpmo", "rktk", "cgyb", "lcpo", "lbkb", "opck", "clyp", "torr", "gytv", "tgmv", "ymrm", "glvb", "", ""),
            // P9 L2: 12c 2e, min 38 moves, dead 28.2% (seed 90007)
            listOf("vypk", "blmc", "btct", "omcy", "gogb", "ryrr", "lglk", "bpkr", "koot", "ygpv", "plvt", "vmcm", "", ""),
            // P9 L3: 12c 2e, min 37 moves, dead 26.6% (seed 90008)
            listOf("ggyb", "koyv", "kmkr", "tgpp", "mbpm", "oytm", "ylbv", "bgov", "pklt", "clrc", "ctvr", "rcol", "", ""),
            // P9 L4: 12c 2e, min 36 moves, dead 26.6% (seed 90011)
            listOf("plyl", "pccm", "ooob", "orkr", "lvyv", "kvtt", "bglt", "gbcp", "kmyb", "mtpg", "vrkm", "gyrc", "", ""),
            // P9 L5: 12c 2e, min 37 moves, dead 29.7% (seed 90014)
            listOf("mcmt", "ckvc", "myyg", "oklk", "ytyb", "vrov", "gobp", "brrp", "rptp", "glbo", "cvml", "kltg", "", ""),
            // P9 L6: 12c 2e, min 40 moves, dead 29.8% (seed 90024)
            listOf("klrt", "poyg", "bvpt", "kgvl", "vtlc", "cmko", "gmcp", "ybrm", "kloy", "cmbr", "gypr", "obtv", "", ""),
            // P9 L7: 12c 2e, min 37 moves, dead 29.7% (seed 90028)
            listOf("cotb", "lmlk", "pmot", "ppvm", "kkrk", "ggot", "lbvg", "rcmg", "bcyc", "vpry", "rloy", "tybv", "", ""),
            // P9 L8: 12c 2e, min 37 moves, dead 28.6% (seed 90031)
            listOf("ytbo", "pvlk", "cgmr", "llvt", "kpkc", "ootg", "rpyc", "ybbv", "opmm", "rgbv", "gctk", "yrlm", "", ""),
            // P9 L9: 12c 2e, min 41 moves, dead 28.8% (seed 90034)
            listOf("gtol", "ktcm", "vybp", "lvko", "kvpc", "bkor", "bcgr", "gltp", "mprm", "ytgc", "brom", "vlyy", "", ""),
            // P9 L10: 12c 2e, min 36 moves, dead 28.9% (seed 90037)
            listOf("tbpo", "pgbr", "rtvp", "yylg", "lbmv", "ttoo", "vmrv", "ycbm", "kllp", "okcg", "cmry", "kckg", "", ""),
            // P9 L11: 7c 1e, min 24 moves, dead 37.2% (seed 90155)
            listOf("tgrp", "grtr", "yotb", "bygp", "poto", "rgoy", "bybp", ""),
            // P9 L12: 7c 1e, min 19 moves, dead 38.7% (seed 90396)
            listOf("ttpo", "pbbr", "rttb", "byor", "gogg", "pypr", "ygyo", ""),
            // P9 L13: 7c 1e, min 19 moves, dead 39.8% (seed 90464)
            listOf("oyot", "pbby", "rrgr", "bpgg", "yttr", "obyp", "tpgo", ""),
            // P9 L14: 7c 1e, min 20 moves, dead 35.9% (seed 90668)
            listOf("ggyb", "bopp", "gttg", "rybt", "port", "ypyo", "rbor", ""),
            // P9 L15: 12c 2e, min 38 moves, dead 30.4% (seed 90669)
            listOf("btbm", "vbyo", "pkvk", "rckl", "klmt", "ltbc", "plmp", "oygm", "cvgt", "rcyy", "pvrr", "gogo", "", ""),
            // P9 L16: 12c 2e, min 39 moves, dead 28.3% (seed 90676)
            listOf("occm", "tylv", "bmkp", "roty", "bkyt", "gopl", "crtb", "ypmo", "lgkg", "vkbv", "rcmv", "rlgp", "", ""),
            // P9 L17: 12c 2e, min 40 moves, dead 31.9% (seed 90684)
            listOf("ypgp", "oykm", "kyvg", "bobr", "vgvt", "lvct", "rpko", "gtpm", "lktb", "rybc", "lorc", "mlcm", "", ""),
            // P9 L18: 12c 2e, min 38 moves, dead 28.4% (seed 90694)
            listOf("ycgc", "lgbr", "vgky", "lobm", "glbm", "kmto", "rkpr", "vctk", "ybct", "ppmo", "rltp", "ovvy", "", ""),
            // P9 L19: 12c 2e, min 38 moves, dead 31.0% (seed 90703)
            listOf("gvlk", "yotl", "rvvp", "ykkp", "ovob", "romc", "mkrt", "bccp", "yrgy", "bmlt", "mgcl", "tbpg", "", ""),
            // P9 L20: 12c 2e, min 40 moves, dead 30.6% (seed 90705)
            listOf("loty", "bcbg", "gyko", "rtpk", "rvtc", "yotl", "lrkb", "mobg", "pylv", "rpcg", "vcmp", "vmkm", "", ""),
            // P9 L21: 12c 2e, min 39 moves, dead 30.3% (seed 90706)
            listOf("vtbp", "brmc", "lvkc", "lokg", "mgyb", "mrvm", "ptoc", "tvbr", "gyyg", "kopy", "trlo", "plck", "", ""),
            // P9 L22: 12c 2e, min 37 moves, dead 30.0% (seed 90709)
            listOf("mpgy", "olop", "gbbb", "yktv", "komy", "krtv", "rkbc", "gpgl", "ctpc", "rlcy", "vvmm", "olrt", "", ""),
            // P9 L23: 12c 2e, min 36 moves, dead 32.6% (seed 90712)
            listOf("yglg", "pcbr", "kkvc", "bgtr", "omkv", "otyo", "rrpc", "kmyo", "lltp", "bpvc", "tbgm", "mlyv", "", ""),
            // P9 L24: 12c 2e, min 38 moves, dead 32.3% (seed 90720)
            listOf("lymk", "lggr", "vmty", "mrbt", "obvl", "grcp", "cory", "cobt", "lvco", "ppmk", "ptgk", "bykv", "", ""),
            // P9 L25: 6c 1e, min 18 moves, dead 38.0% (seed 90731)
            listOf("yopo", "orbp", "rygr", "gbob", "pgyy", "prbg", ""),
            // P9 L26: 6c 1e, min 18 moves, dead 41.0% (seed 90742)
            listOf("oogy", "rypy", "bpbr", "yoob", "pgbr", "grgp", ""),
            // P9 L27: 6c 1e, min 17 moves, dead 41.1% (seed 90777)
            listOf("rryb", "prgo", "obyp", "rgyy", "gbob", "oppg", ""),
            // P9 L28: 6c 1e, min 16 moves, dead 44.2% (seed 90801)
            listOf("prgg", "yyrr", "pooy", "gbpo", "brbo", "gpyb", ""),
            // P9 L29: 12c 2e, min 38 moves, dead 34.7% (seed 90802)
            listOf("pktr", "ymbm", "vgpg", "tctg", "bcoy", "mlog", "ckyp", "yvro", "lrom", "prbk", "vllb", "kvtc", "", ""),
            // P9 L30: 12c 2e, min 38 moves, dead 35.0% (seed 90815)
            listOf("lvol", "rkco", "rkpp", "ltgc", "gcbk", "otgm", "kmcb", "glob", "vbmv", "mvtr", "typy", "rpyy", "", ""),
            // P9 L31: 12c 2e, min 39 moves, dead 33.3% (seed 90838)
            listOf("cvck", "lmrb", "bkvo", "koyg", "pcro", "btct", "ygtr", "vtyb", "rlmm", "olgy", "pgml", "vppk", "", ""),
            // P9 L32: 12c 2e, min 39 moves, dead 37.3% (seed 90840)
            listOf("llgm", "cvct", "bylr", "vyor", "molc", "ktbm", "rpbv", "gpky", "kmpr", "gtbo", "ytkc", "pvog", "", ""),
            // P9 L33: 12c 2e, min 38 moves, dead 37.2% (seed 90845)
            listOf("ptkc", "mtlv", "bvgo", "rlkr", "vylm", "cvoy", "tkto", "rkgy", "lpcb", "mcbm", "bygg", "ppor", "", ""),
            // P9 L34: 12c 2e, min 37 moves, dead 35.5% (seed 90850)
            listOf("tmcl", "lprm", "ortl", "ovvk", "mryc", "gglc", "mkbp", "pkto", "gcgy", "vyyp", "btrb", "okbv", "", ""),
            // P9 L35: 12c 2e, min 37 moves, dead 39.0% (seed 90854)
            listOf("ylvp", "cobb", "cptv", "yylr", "mvkt", "okrb", "vppg", "tkgm", "rmkc", "olbc", "tyor", "lgmg", "", ""),
            // P9 L36: 12c 2e, min 36 moves, dead 38.5% (seed 90857)
            listOf("mcyy", "ocog", "glyv", "trgm", "kvtb", "rolb", "yrvg", "rtpk", "llvp", "cckk", "bpom", "mtbp", "", ""),
            // P9 L37: 12c 2e, min 41 moves, dead 34.2% (seed 90862)
            listOf("rpcv", "rpyg", "lymt", "lmbv", "borc", "lygt", "tpcv", "gykb", "mprc", "klko", "mvgo", "obkt", "", ""),
            // P9 L38: 12c 2e, min 40 moves, dead 36.4% (seed 90864)
            listOf("olpo", "mtgt", "krml", "cyry", "yogb", "klkl", "gvvy", "pcgv", "bkto", "crbb", "prmp", "mtvc", "", ""),
            // P9 L39: 12c 2e, min 37 moves, dead 33.4% (seed 90867)
            listOf("pmkp", "ggpb", "cgrl", "kbpr", "ycvy", "bcov", "tbom", "omtv", "mlko", "gvlr", "tyyc", "ltrk", "", ""),
            // P9 L40: 12c 2e, min 39 moves, dead 37.5% (seed 90891)
            listOf("ktrm", "cvco", "bmlk", "ltvc", "gkkt", "bpyt", "mpgr", "yyob", "gyro", "mlvl", "bvoc", "gppr", "", ""),
        ),
        // Pack 10 - Extreme 2
        listOf(
            // P10 L1: 12c 2e, min 36 moves, dead 36.3% (seed 100000)
            listOf("gkoc", "ptly", "oyck", "rrrm", "pmmt", "bbgk", "yvgy", "oklo", "lrvc", "cpvg", "btpv", "btml", "", ""),
            // P10 L2: 12c 2e, min 38 moves, dead 38.5% (seed 100001)
            listOf("gpbm", "gppc", "govl", "clky", "grmc", "mpco", "tlyv", "yrvt", "vkrb", "rbbt", "okmt", "koly", "", ""),
            // P10 L3: 12c 2e, min 41 moves, dead 34.7% (seed 100004)
            listOf("cobg", "gbpt", "tmtg", "rblp", "kyol", "rvyb", "rvpm", "kmyc", "vvyg", "tlco", "lkmk", "rcop", "", ""),
            // P10 L4: 12c 2e, min 37 moves, dead 34.5% (seed 100007)
            listOf("rcom", "gbpb", "glol", "gkmk", "koyr", "omyr", "yptc", "ccrp", "vtll", "gpvv", "mybb", "tktv", "", ""),
            // P10 L5: 12c 2e, min 35 moves, dead 34.4% (seed 100008)
            listOf("ctog", "gylr", "vvly", "pmok", "crrv", "kytt", "bvpb", "otgb", "mlyp", "mmco", "cblk", "rgkp", "", ""),
            // P10 L6: 12c 2e, min 39 moves, dead 34.1% (seed 100015)
            listOf("vlbm", "rcom", "ypgk", "tlrl", "yglm", "tyko", "gtbt", "copr", "kvrc", "kpgv", "pcbb", "mvoy", "", ""),
            // P10 L7: 12c 2e, min 40 moves, dead 37.6% (seed 100029)
            listOf("pbpt", "grbv", "cmro", "yvtr", "kpkm", "ylgo", "cmll", "gbyb", "ckyl", "vmtr", "togk", "vcpo", "", ""),
            // P10 L8: 12c 2e, min 40 moves, dead 35.5% (seed 100033)
            listOf("rktt", "lpcg", "ykmr", "yrkt", "pcbc", "gvgl", "ybmc", "vomb", "vpbo", "rtgv", "oypo", "lklm", "", ""),
            // P10 L9: 12c 2e, min 38 moves, dead 39.8% (seed 100039)
            listOf("btyc", "mpbl", "vygb", "cctr", "cmyk", "pgvg", "mgro", "rprk", "lpol", "lomv", "otkk", "tyvb", "", ""),
            // P10 L10: 12c 2e, min 36 moves, dead 40.0% (seed 100042)
            listOf("pkll", "mvgv", "byot", "mtpo", "ptty", "bcbr", "lymo", "vglm", "rcgb", "rrkk", "vypk", "ccog", "", ""),
            // P10 L11: 6c 1e, min 18 moves, dead 41.5% (seed 100089)
            listOf("yrbr", "rpby", "gboo", "gppy", "bogy", "orpg", ""),
            // P10 L12: 6c 1e, min 16 moves, dead 44.1% (seed 100100)
            listOf("prro", "rbpg", "yyoy", "bygr", "pgbb", "gopo", ""),
            // P10 L13: 6c 1e, min 17 moves, dead 54.2% (seed 100106)
            listOf("ybby", "ggpr", "ooyo", "grgp", "byrb", "orpp", ""),
            // P10 L14: 6c 1e, min 15 moves, dead 42.1% (seed 100132)
            listOf("bopp", "ggyr", "ooop", "rpyb", "ryrb", "ygbg", ""),
            // P10 L15: 6c 1e, min 19 moves, dead 43.9% (seed 100160)
            listOf("bory", "oybp", "gpgb", "pybr", "gypo", "gorr", ""),
            // P10 L16: 12c 2e, min 38 moves, dead 41.7% (seed 100164)
            listOf("lyyr", "vbbk", "mvrg", "cblk", "potm", "crkt", "mctv", "rgyo", "cokm", "gpvp", "typl", "gbol", "", ""),
            // P10 L17: 12c 2e, min 40 moves, dead 39.2% (seed 100175)
            listOf("rtbo", "llbm", "rkpc", "rvmo", "gpyp", "tlcl", "vmkp", "gcov", "bgrm", "tcyk", "obgy", "vykt", "", ""),
            // P10 L18: 12c 2e, min 37 moves, dead 44.4% (seed 100176)
            listOf("opbv", "crgp", "oomb", "tpmt", "vvyk", "glrk", "yrbg", "ybvm", "kmkl", "gptr", "tccc", "yllo", "", ""),
            // P10 L19: 12c 2e, min 38 moves, dead 38.7% (seed 100192)
            listOf("pbtl", "oggo", "tgmk", "rvcv", "brkp", "byvt", "tpmm", "kvlb", "orlp", "corl", "mycc", "kygy", "", ""),
            // P10 L20: 12c 2e, min 40 moves, dead 38.3% (seed 100193)
            listOf("rlvl", "cgbo", "kygt", "ykty", "moml", "tggk", "rpvp", "bypb", "ropv", "klvc", "mcmt", "crob", "", ""),
            // P10 L21: 12c 2e, min 39 moves, dead 39.2% (seed 100194)
            listOf("ppbm", "ycky", "byok", "blor", "tblt", "cytg", "tkov", "mpro", "mlgv", "krlg", "vcmr", "gvcp", "", ""),
            // P10 L22: 12c 2e, min 42 moves, dead 38.9% (seed 100197)
            listOf("rytp", "bgcm", "ogcm", "btcy", "mvlb", "krcl", "tvpk", "lvyb", "tpgp", "ogyo", "okmr", "kvlr", "", ""),
            // P10 L23: 12c 2e, min 41 moves, dead 43.2% (seed 100202)
            listOf("cyrt", "grkl", "lvgo", "vcol", "clvm", "tprm", "yvom", "tbkm", "yrbp", "cpbp", "kbkt", "gogy", "", ""),
            // P10 L24: 12c 2e, min 39 moves, dead 42.5% (seed 100205)
            listOf("kotr", "tgcl", "kyyc", "pvyr", "cbkr", "ybbl", "tgpr", "pmoo", "lmvc", "mpbv", "lmvt", "kgog", "", ""),
            // P10 L25: 12c 2e, min 35 moves, dead 40.6% (seed 100219)
            listOf("oror", "ccvo", "gbvk", "krgp", "clmc", "ttby", "lvgt", "ygpy", "bmmm", "kkyl", "rpvb", "lotp", "", ""),
            // P10 L26: 7c 1e, min 21 moves, dead 47.8% (seed 100280)
            listOf("ogob", "prgb", "ytpp", "rygb", "orrt", "gyty", "ptob", ""),
            // P10 L27: 7c 1e, min 18 moves, dead 48.6% (seed 100330)
            listOf("oopp", "gppo", "byyo", "gtbt", "ygtr", "ybrg", "tbrr", ""),
            // P10 L28: 7c 1e, min 22 moves, dead 53.0% (seed 100367)
            listOf("rypy", "otbp", "tpot", "goob", "rbyg", "ygtp", "grbr", ""),
            // P10 L29: 7c 1e, min 23 moves, dead 45.5% (seed 100370)
            listOf("toby", "rtyr", "opog", "ypgr", "bpbp", "gbty", "tgor", ""),
            // P10 L30: 7c 1e, min 22 moves, dead 50.0% (seed 100385)
            listOf("ogbp", "yrtg", "ptgo", "rpyo", "tbry", "bbpt", "yogr", ""),
            // P10 L31: 12c 2e, min 38 moves, dead 43.7% (seed 100391)
            listOf("cvtr", "ctml", "pkmk", "ygkt", "vvgo", "rygm", "bpbr", "mtpy", "klyo", "golp", "oclb", "cvbr", "", ""),
            // P10 L32: 12c 2e, min 38 moves, dead 45.6% (seed 100404)
            listOf("ppty", "gyky", "pvtr", "rvom", "rrmk", "obog", "klgt", "bbvc", "myol", "gclc", "ktbv", "mpcl", "", ""),
            // P10 L33: 12c 2e, min 39 moves, dead 42.8% (seed 100413)
            listOf("kpmv", "mybo", "lbpt", "vgcr", "crgl", "ybgt", "gtyp", "ropc", "ckmm", "krto", "kybv", "lvlo", "", ""),
            // P10 L34: 12c 2e, min 39 moves, dead 44.3% (seed 100421)
            listOf("tybl", "bckg", "tkpt", "yvco", "povm", "cplk", "vlbo", "gmok", "gvbr", "trcg", "rrpm", "myly", "", ""),
            // P10 L35: 12c 2e, min 39 moves, dead 46.1% (seed 100425)
            listOf("klmc", "mccr", "ympv", "gtgb", "glvm", "yckt", "ptrb", "ooyp", "krbt", "orlv", "bglk", "pvyo", "", ""),
            // P10 L36: 12c 2e, min 40 moves, dead 45.6% (seed 100439)
            listOf("tpbm", "rovt", "lrmv", "lytg", "okgk", "bvmo", "pcob", "ykpg", "rcpk", "lrcg", "tmvy", "cybl", "", ""),
            // P10 L37: 12c 2e, min 38 moves, dead 44.5% (seed 100454)
            listOf("kgov", "pbmy", "tgcb", "otrl", "plgb", "mktl", "cyry", "prov", "gmcc", "pvrb", "lkky", "mvto", "", ""),
            // P10 L38: 12c 2e, min 40 moves, dead 45.4% (seed 100467)
            listOf("lykg", "oprg", "rgll", "oyvb", "cbmt", "cmvo", "gmcy", "lptv", "rtbp", "ckyk", "vobr", "mkpt", "", ""),
            // P10 L39: 12c 2e, min 37 moves, dead 49.7% (seed 100492)
            listOf("cbbc", "yyvo", "rglv", "lymr", "ptoo", "vobg", "pcrm", "lmkc", "pylr", "tbtg", "pktv", "kkmg", "", ""),
            // P10 L40: 12c 2e, min 40 moves, dead 44.6% (seed 100493)
            listOf("klry", "oycb", "vtcl", "cpbg", "gctg", "pmlg", "rvkm", "poyo", "vmtr", "vbyr", "kkto", "mlbp", "", ""),
        ),
    )
    val hard = listOf(
        // H1 (seed 900000)
        listOf("kgpbgytovpmo", "mllvkmkbolvr", "pkyvmcpgvtop", "mtcgrlryccly", "mprvyovryyvg", "cbgvvkpctkrb", "bgokbybmvplc", "ctgmoybygoll", "gtlroktmckrp", "ptcotgbtmybl", "rltvopryrlpg", "crokcktmmbbk", "", "", "", ""),
        // H2 (seed 900001)
        listOf("gogpltgkgtyk", "vgktcboymvrp", "tbprookgcrml", "krvvbmbygyrv", "cvkvyvrgrlcl", "bcrltrpmppgk", "mvylbyocltlm", "mtcokkkklbcy", "ybbpbttvgmvo", "tcgrymptptmc", "lkbporcormyo", "pobocygvllmp", "", "", "", ""),
        // H3 (seed 900002)
        listOf("clboogpgpobr", "ocykgktbmbvo", "brcgbmvmtkmy", "mlbplvoygyto", "cykgbooglvkt", "pmlylkccopry", "povmprtgtvvo", "pykvlmrclprb", "tbtymvctcllr", "mrrcgkytvlpr", "ytgrlkpkpkvg", "cbmrybcgkvtm", "", "", "", ""),
        // H4 (seed 900003)
        listOf("gpopbbykmvmg", "vtrkkgpbryro", "mkbcvplytlcr", "vybpomoocllb", "ptcrtctggocc", "yvoyrcoktrlm", "crppmlpblymg", "mglbtkkrgbmv", "kktgootylpvm", "pygptmlckcvb", "vlktmlvtovbg", "kcyygrryorbv", "", "", "", ""),
        // H5 (seed 900004)
        listOf("ktlpprcccvtv", "oytcryvlkkvk", "kmtbrmgbplyl", "rgklcbvrpkbg", "prbklgmlvbgt", "tbcbrvtvgolr", "yokopmkckymc", "gyvbtllmprmo", "oyogpmtpkyry", "ovmmlyclvotc", "pcpbogovmggb", "gbyttomrrcyp", "", "", "", ""),
        // H6 (seed 900005)
        listOf("rgklkppmcprl", "krrmrgcmtttt", "vlvcogmlpvyy", "lymoppbrvllp", "bltbgmktbckc", "mpybyrmkombo", "oomyovocytvg", "mlpcklmovkyg", "vrbltvpbvrpr", "krcgbgkcroyg", "kbgvybcgbcyc", "ptttooklygtv", "", "", "", ""),
        // H7 (seed 900006)
        listOf("mkggkcpvrbty", "votprkyyllto", "kbklmkyrgpov", "ggcllvvolcgl", "ctvkpyloppyc", "bbpmbgovtybr", "rmmrlormbrky", "mglpgrkykctb", "bvcobcvpvopc", "vggrmbrbtttr", "tvgpymokcttl", "ymymcpcoolkm", "", "", "", ""),
        // H8 (seed 900007)
        listOf("tgorplckycvb", "omrkbgycpblc", "bmcyyvmbommp", "octbgctkypkk", "grkmgvmotlcv", "pyvtkytptplc", "obygkkyrlycb", "plbrmmrlbppg", "lgtgmtblvork", "kotrcymgrylo", "vvpgovtltolr", "mvcgvkropbvr", "", "", "", ""),
        // H9 (seed 900008)
        listOf("ylcmlbclvomm", "gotrrobrlyvg", "kpgbyrmmpbrt", "vlvkcgpgormt", "vgopvcvykbgc", "cmppkrclbbpp", "tvkltkytrtgk", "rgovlcobmlyt", "ocmkltoyvgyt", "rgkmpcvytorl", "bckmltycrgbm", "pppkokbbyvyo", "", "", "", ""),
        // H10 (seed 900009)
        listOf("yplvbttrcklv", "vgrpykmlrmtp", "tmbmromkyrgo", "ptvgvbclkgyo", "rclpmvtocbyt", "gbcmopvkolbm", "tctlyootmyym", "bcrpcrylrkkl", "myybybpbpbkp", "kgvbcltglmct", "gorocplpvrkg", "kvgcgvkrgoov", "", "", "", ""),
        // H11 (seed 900010)
        listOf("pcgbpryvcctr", "totgpcotgtgt", "tmvrvrmcrmpo", "cmyrllblolll", "vbvogvycktog", "ytylopvkmvby", "ptrvryvtmmvy", "kcmkcrmkylbl", "ccykggmmbbcr", "bloopgokbrky", "pybkbpmglvpk", "kolbpotgpkrg", "", "", "", ""),
        // H12 (seed 900011)
        listOf("ylpvlmcvgcpc", "lvovocbtolbo", "pmgvtllkylmy", "yctcmyrrtkkv", "rkbctykvtvrt", "ktvoclgtvrkt", "mtcgporlbgkm", "ogpokyoprlpp", "bckypmpvlyco", "gpbgbbyrrgbc", "mgyyvrgrkbml", "kbtmomrogpmb", "", "", "", ""),
        // H13 (seed 900012)
        listOf("oyloylobcmyr", "gbrvbltoltkv", "mptmkbvytoyl", "pmlkcygvktgb", "mpbtgycygttr", "crrtpmgkcmko", "vbpvmcplcvgo", "ktgmryvgrpyb", "ycgvbkolkkkb", "mrmolvovtcoc", "kcrbgpmtbrll", "cgpppyrprlvo", "", "", "", ""),
        // H14 (seed 900013)
        listOf("glloblbyvlvc", "pvoyckgvmorb", "bkymklrlgrgc", "ytmggmykvprl", "tgtbtvvlmpbb", "rpocyoyroypc", "ptkykpblmkvr", "tkttgbmvctrv", "tgytmbpcobcb", "mmmrrkppyovp", "lklgkocctrkg", "ocymopvoclgr", "", "", "", ""),
        // H15 (seed 900014)
        listOf("ogrvkyvkymko", "gobptttrbmvr", "cvrygovlmgrr", "ytlklgcypomy", "lltbvltkkpmk", "mcpoktrbpglm", "pgcoktrbyyyl", "toogrtctbcvg", "lmyykymcgbvc", "pvcrcptcobpc", "lklprgovmmmb", "rgpbvkobblvp", "", "", "", ""),
        // H16 (seed 900015)
        listOf("gormyttloyrm", "rmokccvvgkgt", "omgpyotltlmy", "bgklplgcmycr", "lrtgvrcmpprc", "rkkogltvvybp", "cmybkvppprmt", "yrvtlyygtbol", "klrcyvgppvpv", "btbvcckblkmk", "gyokcbvboopt", "gbobmobmklcr", "", "", "", ""),
        // H17 (seed 900016)
        listOf("ppbmgccryvlk", "ctmctrvtbrvc", "ooylrgmpmlkk", "tktmptlvgmlr", "lobooytpclyb", "mcvmymptbott", "oykkcbrvgcbb", "yoyglolmgrgm", "pppcrgvkkyvc", "lbropkyyrkrb", "ptogpvtvkmcy", "gvbgokbvlgrl", "", "", "", ""),
        // H18 (seed 900017)
        listOf("bggcpmvyybkg", "rorgbymkcrmc", "tkkbvopcylyt", "mvrtcoktgvlc", "crlvkovlllgr", "bgvlppvkcoym", "ytbrrrybmckg", "mmypopmtokoc", "lvprpvtttykk", "pbtrlomlmvbc", "ggplmopyotrl", "pbgbgktvcoby", "", "", "", ""),
        // H19 (seed 900018)
        listOf("mgvtccbpyypt", "rlmlcgylvrmv", "rcrboctrvbco", "vtbgomklpogy", "ppgpgckgpkrm", "lpcolybgrykp", "lkvvpgbbyvko", "krkkycrpmgvo", "rtomoompoyyt", "vbmccmrvrylg", "ttbtlblckgmy", "lbkkbotmttvl", "", "", "", ""),
        // H20 (seed 900019)
        listOf("gbbrmlvvocoy", "ogobkrrkgcvl", "mvrptmpmptyb", "lbggycottbpk", "ypvgrvcyytky", "crkoglvkcrpy", "otpcogvmtmgy", "ompbccbytktm", "rrcbbgtkcomp", "lvkkltypktlv", "llgrmvgklcmm", "lyprplbobvro", "", "", "", ""),
        // H21 (seed 900020)
        listOf("rgvkkgvkmlpc", "mgogrplgmrbl", "ocmptvytkmpt", "troyrrctmrmy", "tlkpkpykggro", "gcrpgbylcbky", "rovvokcmvlmy", "cktrbgcpgycv", "bloctgyvboyb", "tpcyvrltvtmk", "lvbpbvooclop", "oyblbmlktbpm", "", "", "", ""),
        // H22 (seed 900021)
        listOf("mtmyrpryoclc", "lbvltbpmbopv", "llrpcggtlvvc", "ggcrolmpbkkt", "pmogbkyrtmct", "rvkpgolvoygb", "pctvrygbkcmb", "yyoblyrbtvgv", "kvtmckooptlb", "rktrmcllovrb", "yrggkopykcmk", "vymgomytckpp", "", "", "", ""),
        // H23 (seed 900022)
        listOf("pvtgpyotvmtc", "kvytmtolcocb", "yyppcpboblkk", "pgmprltrcvmc", "grpgymvtkgor", "rlbkmggrvmlg", "bylgpkkvkkpm", "pombmrylrbol", "ymgvcomvortr", "kvbcvgclogtl", "yyoorcvtybtk", "bbykctpclrlb", "", "", "", ""),
        // H24 (seed 900023)
        listOf("cyolpvmkotrv", "ggkmrkgcyybl", "rlrcbcyvvvbb", "tyvoktlbtblc", "kkgobomportr", "mogpooglmtrg", "rkkpypgprtyp", "bgcbmpblcopt", "okpmykrpgctv", "mgtbcmlkgmvo", "tmpcrllkvclt", "lrvcmybyvyyv", "", "", "", ""),
        // H25 (seed 900024)
        listOf("ckvyrlyoyyct", "rpttokmbtlpb", "rybrvtpvlrkb", "mgmlgomprpkm", "otgmctbmpoyv", "rrtvogllolvo", "ytcrcclmktbg", "cycbmcyrllot", "bvogpbovmblm", "vkkgvgprpkbk", "kcyrkcgctpgp", "pkgmoyvvglyb", "", "", "", ""),
        // H26 (seed 900025)
        listOf("pyrogymrpcbp", "kvytcobkolyc", "yytygkrplpgl", "kbcmrorpycgo", "bybgptrmclto", "vkgvmpmlprvg", "olmmvcltpbmo", "lotckmovrplr", "rrltblklcgvt", "cbvtgyyokctb", "kbrtkkpvbgvm", "mokgvbcyvtmg", "", "", "", ""),
        // H27 (seed 900026)
        listOf("obvbmtykbyly", "prrvmmlcrcor", "rtggylmvlvvt", "rppvobppcgkg", "lylpgvmtygrc", "bmtyvctmooko", "lptmgykryvco", "tolprgbltmog", "bcmcprbpmtpo", "kbcklgkyvrlb", "okvrkmkbcybt", "pokltgcykcvg", "", "", "", ""),
        // H28 (seed 900027)
        listOf("orkpkvctptvy", "tbvlypgkomgr", "mpgocrgmptgo", "tbmovlkclmcc", "bolpbvrtmolb", "bmmyrbpmlcpc", "bycklcmytvck", "kvykkccgymbr", "ogvtpoyogoly", "mlvpgrkyvgtt", "rvbkrlprybpb", "kttllgrgryvo", "", "", "", ""),
        // H29 (seed 900028)
        listOf("tcbpvogvbbbt", "yprlmckmpcct", "ymorgbgppmlp", "gorlpkmkobbt", "mlrmvtprcott", "mylbrlkgkvky", "gmykpybcvobr", "ovymkogovpcm", "vkryygyccyrk", "gyolcvttvgtr", "olmkpbgplbvl", "kvorclgrtltc", "", "", "", ""),
        // H30 (seed 900029)
        listOf("vbmlclyylmtv", "krgklctlmlyv", "vmoclgbvkboo", "rktpvlpgpppo", "vypcbkgbbgoc", "mrkcgtbvtlkm", "bcotyyrmooyr", "cmgykprmcrcy", "tttpvrygyrkb", "mrgvpkoopklb", "rvmltvpcogrg", "mbloktpctybg", "", "", "", ""),
        // H31 (seed 900030)
        listOf("gmkogryrvmlp", "kbtvtpkcktpy", "gvmlrvvvkcor", "mblpkmmokryl", "tkmyokprtpyp", "pgvyvbbtklml", "plkmbglcbryo", "bvtolyckoccv", "lycbbgggoycb", "plgtyrtccvrg", "prmggcprblor", "mttocyovtomb", "", "", "", ""),
        // H32 (seed 900031)
        listOf("myyrtytollol", "tvptvylpyyok", "cvbcbmclrbrc", "bctmgprbkbmk", "grmkckmgvtog", "cgpyvpkvklyg", "oboktbvvygpr", "tcbovvbgppgy", "yrcckbmllcpo", "olrvkgmormml", "ropoblpgtttc", "pkyktvlrgmrm", "", "", "", ""),
        // H33 (seed 900032)
        listOf("yympgykbkblc", "cvcvobgrkcyo", "omgkykgclkly", "ollptgtbgrto", "cbvvmvmbbvbr", "ocrypyppgtbp", "vctgmycymbvk", "omlvkrtmtpot", "kboyyrptcgct", "olvmklkpmgpo", "crrrmrlvgtvl", "ormltpgklrpb", "", "", "", ""),
        // H34 (seed 900033)
        listOf("pbcomcymmgrl", "pmvpvrbotckt", "lklgtgpplcmy", "ktkyyypokokp", "grmylmrppbkt", "mvkmbomgyvkt", "brlrvvcggltr", "ylvrplroclgb", "cctkyoptyvvl", "tgvocbkklbgo", "bocotvgvyyrg", "comrmbbrcpbt", "", "", "", ""),
        // H35 (seed 900034)
        listOf("cbgpgltbvcbo", "yyltrglkyvlv", "oolmlcmoptbb", "clvoyvrgvrbc", "cpcppkogpbyv", "pkybgrrgkomt", "pttmtkkbyymk", "coovrrymgkvg", "ppymvklplybr", "kgbrrcvtocbo", "trkkgycmtotm", "lpcvmmtgllmr", "", "", "", ""),
        // H36 (seed 900035)
        listOf("blblyytlvgcv", "grllcprprmoo", "cgprkmgotklc", "lkcprvyrgrbo", "pclgvrblccmb", "vtcmkpgpptoo", "koomgktklykp", "yvkvmycbotoy", "btpvmrlogvlo", "ggmktybvrpvt", "rmbbkybbrpty", "ctkmymygvcmt", "", "", "", ""),
        // H37 (seed 900036)
        listOf("brlcyrpttokb", "crvtrvobclcb", "mvgcblppmbrv", "oologmgprlyc", "vmlrpkttybbt", "kgkkvgoopvog", "tbrtlpmcmtbo", "pylylvoyvygg", "ylplkmkcptym", "gvpmbkptrrty", "ymyrrkbmvkgc", "vgocokkcclmg", "", "", "", ""),
        // H38 (seed 900037)
        listOf("cvvypctcbpgr", "mkcytvcbrvvv", "mgmklmotoplm", "gombylrlpgyt", "cbcrgptllllg", "okkyomkvklyk", "ypryrbvcroby", "lovmcbvkkblp", "gokctmltykyr", "pgrrgtotgpct", "bgpmprgtkryv", "mbpvoomobbct", "", "", "", ""),
        // H39 (seed 900038)
        listOf("orcggkrpvgcm", "mblckmkovrvt", "gtolbpyypmlo", "ktlgvtkmtctv", "tvrlcomyypvm", "rlgbyblgpmko", "mtkyrovttocm", "yrpbympvvgll", "vktroobgcmvo", "bykyrptbkpcl", "rogcprkbyplb", "lggybkcbcrcp", "", "", "", ""),
        // H40 (seed 900039)
        listOf("clycrpvgvplp", "yktookgvbrrt", "clmvbpkovbpy", "rommvvbmtybk", "rykkgbpcltop", "ooybrgmbbtmk", "ybktclgyvobr", "olcymvgtpokm", "gcvkkcgyopcv", "tcmtrtcpmkmg", "rtorllrrycly", "gbpllggmlpvt", "", "", "", ""),
        // H41 (seed 900040)
        listOf("rmybkoyyborl", "vvllckrcbbrm", "pkkptrmomtvy", "gtcovtcmgvvt", "ytpcykvpglbb", "mlvtgyplkrpg", "vlllcgtrkpom", "porvltrmgcpl", "ppobobkttmcb", "rrgybbpkgktl", "omcogvromkgm", "yyybokccycgv", "", "", "", ""),
        // H42 (seed 900041)
        listOf("cvgtyollrrbp", "mvkporplyyvv", "yplltmboplkg", "ylytgvvgokot", "rbogmvkcrtmr", "ltkvmmmkrcpc", "bgkryvcbgkcv", "ptbkptmcloot", "ymckcggkgbko", "torvmrrggpol", "ctpbyoyyblmb", "rbybmcpctlpv", "", "", "", ""),
        // H43 (seed 900042)
        listOf("otllmkgrgcvk", "pprygogvvgck", "pbbblprmoovp", "orrvtovgtyyr", "lcglrcctcyby", "ykpklvttbbyr", "pmymkckoctmc", "omoplpklovlb", "rtbbbvrlmmkv", "vymblpytgocm", "ygrroyctcpkb", "mgpglvgmtkkt", "", "", "", ""),
        // H44 (seed 900043)
        listOf("pbltybmvkprv", "vybgrvorpmmm", "tgygcpocoyor", "logycypbckro", "mkomtktbrbpb", "vvtpklgmrmcg", "mppkytcglgty", "yrbycopklgyv", "ltkolmlrcptg", "cvkbyotvcgrk", "vpmgovrlrklo", "cbtlctkbblvm", "", "", "", ""),
        // H45 (seed 900044)
        listOf("bmoccmypclvg", "ovcpkrmpkvbl", "ykkglcbtrbkc", "tvygktmmorbr", "rookyopvrtlt", "trgpmgcotyrp", "cvoprlcrblyl", "tmyyotbgtlck", "pcyvlvgbppkv", "okplrtbmblov", "tgmvgoygrgmy", "lypkgmmckvbb", "", "", "", ""),
        // H46 (seed 900045)
        listOf("tclvgvmrmyyo", "pgtglppycylo", "vtgmvlcpbgmo", "mrpogbtrmkgy", "rkymmytrrplg", "bybmtkrcvvlm", "bvvvtbtprcbl", "rotbktcptkvp", "tkgpcocbbomk", "yklrkkykclyk", "rpccycgvmgrb", "vlbolopogloo", "", "", "", ""),
        // H47 (seed 900046)
        listOf("tlbmcyylcrmm", "rbptkgkpkopm", "ocklbkgmvcgt", "ytbcoygvkykt", "ygcyorlkrgbv", "pvkbmmvoytpm", "yrmrgvmllvyv", "lgvvkgtgvcrb", "crcbovobrptm", "tlytrlbppcmb", "oroyolllpcgp", "trppgotbkock", "", "", "", ""),
        // H48 (seed 900047)
        listOf("llbvcgvkblct", "trcvclrtgoyb", "mrlpmocctkgg", "yvyrtrvlymll", "vkklgobboryp", "bogpltrorpoy", "cmvbgbbkmcmo", "ogpmbyccvpmm", "vggyrkottycp", "vkkmtplpycmm", "glbrtrykopkp", "ytgvtkrvpbko", "", "", "", ""),
        // H49 (seed 900048)
        listOf("vobkcgvtkmly", "pcbyltpvoobb", "rkogbopbggbk", "vctvmbopytyr", "rmvmtvcrvllp", "trkoylkmllck", "ktcpkrlmlvgr", "mbmgmybgorlb", "ryggyctcotcl", "bgogtgmovpcm", "mvtptropkrpc", "krpyvplyykyc", "", "", "", ""),
        // H50 (seed 900049)
        listOf("cygpbytccoot", "kglpklvbocgl", "cgolkvmbvmrb", "blkvbptyrtyk", "toplmppprtvt", "rmgokbtrbyrv", "gpgmgkytgovr", "mvtlbrcgmmoy", "kkkloymmbpro", "yvbrclcrcomy", "vkggvtrmvpoc", "cytplkyblplc", "", "", "", ""),
        // H51 (seed 900050)
        listOf("ctlcgbplbvlb", "lkovgvygbykm", "ylbooycctmrk", "tlttrklvckbo", "bvoktgpyokrp", "pglmgvgtrrrr", "ggbppykomcoy", "lybkvmmvctpt", "cmylrtkmcvoy", "boltmtpgcpbr", "pocyrmgrvmvl", "cpkorkvgmpyb", "", "", "", ""),
        // H52 (seed 900051)
        listOf("vylcybvkmomg", "ggbcorccmymm", "vcgloroblrgo", "lrctklpkolcg", "yoyrkrtvpcty", "ymcplcmoppkr", "pobvgbrykmtt", "pttygkggtbpl", "ytvmrvvpgtoy", "rkpmvblylbvv", "rovgckmbprlp", "kblkobckmttb", "", "", "", ""),
        // H53 (seed 900052)
        listOf("cblopkopgmpt", "rogbbbkyrkgr", "ppovpyybmkol", "rtvmltyocgmv", "rrctropkbvkc", "ccborygrovkp", "vbctlytcrlpt", "gmcyvokgvvbg", "mobkpmgrkltl", "mycymlypgvgt", "klcmlvpcyltt", "vrmbbktgyolm", "", "", "", ""),
        // H54 (seed 900053)
        listOf("lokmtrrktyol", "ymcmkyvgtyvo", "cgpkvlgkopmy", "crbgvckkprkb", "pkbboyblpybv", "bbtlvrvmgpbl", "tmykomtpcygg", "vlpvckolymoy", "rbltrbtogtcg", "vbmmocgtymrg", "ollrvcopmgkr", "rtlcptpvrccp", "", "", "", ""),
        // H55 (seed 900054)
        listOf("bvrlpkttgror", "ltbpmggckpkt", "protrrytmrbm", "ykmmgpccgvcp", "cpotgykyplyg", "lvrctblckgom", "vyymlvyrvgkb", "okvmgvkbtobo", "kmlgomryvcvv", "oovgymbkbbtk", "rrpclpmblyyp", "opcllctlobct", "", "", "", ""),
        // H56 (seed 900055)
        listOf("lgvprlclygyv", "tgpbtgvbgopr", "rpgympotmbto", "kmrmrgplvmtc", "rvgbkocrcbty", "lmkvlypvtobp", "cvcpyyrpkolv", "locryvtkmbkv", "tbcokkkylrmo", "cogvyobckrgc", "mtcgobrmlmyb", "lpklptmybktg", "", "", "", ""),
        // H57 (seed 900056)
        listOf("ttlokbmorlor", "rrppvvclblbv", "ytttpbmbrlct", "lrtkyortmbvc", "ytggpygtkkyo", "cgmyolpvkkmy", "ogbobtycycpk", "kbrpgvylkgyo", "kmbpbrcocccy", "vvtlgkmpgkpl", "lvvgmgcogvrc", "rmpmvlrbmpom", "", "", "", ""),
        // H58 (seed 900057)
        listOf("cvrctyckyltg", "tyyboklgcvrt", "lbovvmmckpgt", "kmkmbclprpvk", "colbbrcgybvm", "lkbmoogrlpvo", "yprgoogggbrm", "pmbcgmyvktyt", "tlkgvtppyopt", "plcckloorktr", "pblvyrmgycry", "kovprtbmvmlb", "", "", "", ""),
        // H59 (seed 900058)
        listOf("lcltrpmtmrry", "crtogblgopmv", "pkvlmpcybtcr", "lcgbgmpovrbp", "ovvvryrcmvlt", "glgbpkvtypoc", "tbbymoyvccrm", "vyyomoygcbkl", "byokklrttkko", "cmlgmkyrykbb", "glottpgklpkr", "ckbggtvopvmp", "", "", "", ""),
        // H60 (seed 900059)
        listOf("cbcpbttmrvmp", "gtmgygoobkmm", "gtyrppcmgmcb", "kyrkkyvglcmo", "promrlgtokll", "kgktryyvbbov", "ymbcrrgvkvmm", "olbyytvopttg", "llvtbppcyvrk", "oogvkrctbkll", "pplccoolbbpk", "rltpcgrycyvv", "", "", "", ""),
        // H61 (seed 900060)
        listOf("ycmcctoltmro", "tptkomvttvgb", "krcmyttmyocy", "tbrvkgvgybgl", "polmkbrcgbby", "ogmykycokrbm", "mopvlckotoly", "vclgycbrptyk", "pmcvvrpoglkl", "blbvkpbgrpro", "bpgtgvlylpgm", "kvvpkrrlpcrm", "", "", "", ""),
        // H62 (seed 900061)
        listOf("rcklvtrbpmyk", "vlpccpbvcyvl", "gcrtbogcygby", "vmmrrcrgglkb", "yccvmvocbbvy", "ootygolybmyr", "lpptlpvblptk", "lvkggmkmrtkp", "cgoprmkgooko", "pvytrcmgkklm", "tbtmolootkym", "ryrbvbgtlppt", "", "", "", ""),
        // H63 (seed 900062)
        listOf("vykbckmvyvmb", "rlrtoklvtcpy", "ggcpgcobmrbl", "ypltgrkmgvtp", "byoltpbokgcc", "pogkyktlrvrt", "krmyycmmkpcv", "vrcctrgctotv", "roygrcovyobv", "lmmmoklpvymb", "lmbokgrlobbk", "blgppgttplyp", "", "", "", ""),
        // H64 (seed 900063)
        listOf("yyglmbltkpyp", "pcglblrtkkkt", "vkvooybtbtrg", "lbcgymycccov", "ollvbcclmlrr", "orpbgmrrbmmb", "grygtmcttkcb", "otkrvyyokpbv", "pggkmtbltrmm", "rykpvkvyvolk", "ovyorgltvgcp", "popcmpcgvpmo", "", "", "", ""),
        // H65 (seed 900064)
        listOf("cbygbovbkctk", "gbtmrcvcorgv", "pmcctcgoprok", "bckrrrcmlktv", "pbyrvrtgbkrb", "mpkpylgotpyb", "llbtlbmyklkb", "gtcokpvpvmty", "vkvglgmmvpog", "kllcpttogyvr", "mytpoolymmlg", "yymopvcyrrlo", "", "", "", ""),
        // H66 (seed 900065)
        listOf("vbyvlorrcrpl", "lrltmyvgkcmc", "lopvcppglrpk", "ptcvbbyybymg", "kmvolkorctoy", "tyvcctcgktto", "ypgcvprbgoyg", "rgbgktgmmbyl", "vrcmtotbtykl", "mpoblbropkmv", "mpmrmkpotkrg", "kbylovgvbckl", "", "", "", ""),
        // H67 (seed 900066)
        listOf("rbtmkrvtgyoy", "vkybvogpocbg", "olryrcprytty", "rctlmvcvoycm", "vcvkkcvblbkt", "bmgmrmokmtmk", "mcbvbtptpcgo", "gogpolorkmll", "bmvyylvpmpbb", "grktclpgrpll", "opryprylbccg", "oytktkgvpglk", "", "", "", ""),
        // H68 (seed 900067)
        listOf("pkcbpbkrmlcp", "cklkbyggrcog", "lmkcoboclvkc", "rmkpvrcbyyvg", "cyvylkpyvtog", "ytotrvglmvov", "kymmbcborcgt", "pmlmpooybvom", "rbrbytgtlgpt", "pvlptrgmrtml", "tkylpvttpkrr", "vyokcmobglbg", "", "", "", ""),
        // H69 (seed 900068)
        listOf("vycgbtotgbro", "gtrmvygovpog", "gybccovpklkt", "tktyvppllpob", "mmrvcoymbolp", "vpcplkkcypbm", "blbgkctoctbo", "rrmrprcmglky", "rkrtkcvgtlym", "mrpymgbmlkyk", "vbprttgylgom", "ockycrvvvlbl", "", "", "", ""),
        // H70 (seed 900069)
        listOf("lgpkovbtoryg", "gbckklbkpbol", "mkomckpkllkr", "crmgtgmtkgvg", "yccrrlbmymvp", "rtgpvrgyobol", "gmtyypptvoov", "mtvlkcclmyyt", "lcttycrcbplp", "bpkoorbybrml", "yovkgtrvcbpb", "prgvcvomvtym", "", "", "", ""),
        // H71 (seed 900070)
        listOf("vbmmmvllkprg", "pppcoggvvyck", "okycctyvgkbp", "rvlrmvmtgmmm", "brlottvkbgty", "yoopbcbtmrly", "kglbbtcrgtgb", "govgytrtkkcc", "blvvoybroppy", "kklymlmkpbcg", "vroolmtkppcr", "coyyrlpoltrc", "", "", "", ""),
        // H72 (seed 900071)
        listOf("lcrvygvlvkyv", "ckygkgmmpvpr", "bctbmggcpkmm", "mmbklcytbotk", "tmpgggrcbylg", "tyblmlckcbkp", "lcprpvvpykrb", "ygpbyrvtytoo", "oorgmtyvobco", "ocrtbgtbvvor", "rlplrollokck", "mpvkyotmpltr", "", "", "", ""),
        // H73 (seed 900072)
        listOf("yrtcgvcomlcy", "ltgkvytpolky", "grbtvmvbbvyt", "mpprcgmygkty", "kpvkpomvgbrc", "ttgpvovryppb", "tkkmllbrrpbk", "ottomcpgmror", "ylbkvyplcclr", "vogbrblcgybk", "mmcgylgmmcor", "lolbkotkvopc", "", "", "", ""),
        // H74 (seed 900073)
        listOf("mmtbtbokoyrr", "cotykmppglyb", "cgpkgmbvomll", "pppybtolvmrp", "octovpclbrmt", "kcrbbopockgg", "gttkryttrylv", "cggckmyvpmcv", "yvgkbkmmrlct", "rorcclvygvyb", "rlrvpmvptoov", "gykblklklybg", "", "", "", ""),
        // H75 (seed 900074)
        listOf("goccmkrmytpy", "tcyooroggptc", "ylvprgtkkkvp", "ckbrmtmclgly", "obpmrvtbpvpv", "lvytobcobkcm", "omvmrcoyyyyp", "oltmplclckrg", "olrrgklomckl", "tpkbrgbgmvvk", "bpbrtvgbvvgy", "ytlbkgrlptmb", "", "", "", ""),
        // H76 (seed 900075)
        listOf("grtomrlrpvkm", "pvtglycogkyy", "gbocvprvklvt", "bmpymcbgocyv", "gytkppybccpl", "kvtmoktvlblt", "pglokcobkrmc", "pkovoptlpybb", "tlrtmbogrktv", "ktrycrgrgmcl", "mrygycompbgc", "kryolvbbvlmm", "", "", "", ""),
        // H77 (seed 900076)
        listOf("grkvmrpcpykl", "tokgcvbmbprc", "cpotvlkyyolk", "pvbgltmkkmtb", "mygmvlvtgyvr", "cgobkpkyovcc", "rmporbygybrp", "pvvltoyvpgll", "ktcmbcbyttmy", "mlggyombtvmk", "ccrorglpbkor", "lrgpobrtlcot", "", "", "", ""),
        // H78 (seed 900077)
        listOf("gppggckoglbl", "lokgblpvmvlt", "kggpykrbkmlr", "kocvmrpvrgmg", "tobmylrmrpyp", "rovbtocokytc", "mbyvyvkglrry", "pkmpocbgobck", "prtgmlkclrvc", "vtrttpymctyy", "tbcvccbmlovy", "tpbmkyotvlbo", "", "", "", ""),
        // H79 (seed 900078)
        listOf("tbrtclktmggo", "plyopobybvrv", "vpggkbcpptbm", "mtkrblmkvloo", "pvpgmygtgmyt", "mcokccbmkcvy", "lmyvobplgtyc", "ptvvtorrlvcp", "ogrvrkormvyc", "lcbrgkrtkoyb", "bcgpklbrmtrl", "gllokyyykmpc", "", "", "", ""),
        // H80 (seed 900079)
        listOf("ptomkmoctbgk", "ompcrlklvvto", "kbovppgmrblr", "cgookgmbygmo", "pvvmgbvlprpp", "ygtpcrrlrobt", "vryctpgcycyl", "pctrmkgcymmk", "lmovocbbglyo", "byttkmlycypk", "crbktlgbvvrk", "tlkrlyvygbvt", "", "", "", ""),
        // H81 (seed 900080)
        listOf("lytogvmgktbm", "mvgmbttyvypo", "klppkbpckryy", "lylmpobvlror", "yogogtrtbbky", "oklbtpplmolv", "opmmyvtlrbml", "gkbcylmvgrgp", "prvyyrtmtkmk", "bvcccgccrovp", "orolbcvgpckc", "ccbkrttrvggk", "", "", "", ""),
        // H82 (seed 900081)
        listOf("pkborbclmblv", "bogmbopytlkc", "vtrlcgbpllbt", "gmpvkypkmybg", "tygtttbgrorp", "lvkbmprkoylc", "mmcpvpmrmyty", "corpblmytcvo", "vmomvctgklcr", "rkpvrkcggoty", "ooggckvokvyy", "blltpycrkgrv", "", "", "", ""),
        // H83 (seed 900082)
        listOf("gbpcgoglbkgo", "klbbvllyotmo", "cvvymbybpyrk", "rgpmkvrpmbtt", "oclotctlvvmp", "polymgcoktvk", "mrpkmvpooktr", "lmgbmrykccvp", "gyrrtgvrocrg", "mlbyvtlcokpc", "yyrgcbtlpkbr", "bpttvmcyglyk", "", "", "", ""),
        // H84 (seed 900083)
        listOf("prvgvblvckmy", "kovkployolrr", "gbyrogppkbgv", "trorpmcoyocg", "vmpgkrtkrkpm", "lrbtcclybttp", "pgcpomvckymy", "ymbkmltycllo", "tbtbgllytvgm", "vgcrggmklbvb", "blvkpyckttoy", "rcootbcmprvm", "", "", "", ""),
        // H85 (seed 900084)
        listOf("gvgkpgbgoocr", "tgcrrmmlyylr", "lrkrokcmpvcg", "cvpmgblyyrtk", "blotypmgvtgt", "pmvlrlmmgboc", "orrykvktokyy", "cpkygmttyccr", "bykvlbpmtvbc", "tbpotvpbpplm", "lbylvcooklpr", "btcgombvkkov", "", "", "", ""),
        // H86 (seed 900085)
        listOf("okmyyytlyplb", "mbcrbgtorpml", "mtpbvcrmtlcv", "govyogmvopob", "pkrkbptvrocy", "ckmtcbyptkvl", "lcbcmgollotg", "lktlcgmgkvtg", "bykrgptkbkrg", "yckmckmrgryv", "rlmpgtoyyplv", "bvcrprvobvpo", "", "", "", ""),
        // H87 (seed 900086)
        listOf("lyrovmkpotkc", "gotooocycpym", "orvrtbvbbgcp", "llvlgmkgykbt", "vmppgcclyvom", "bclyrtgvvgbr", "mkvcrgcpgvbt", "lrbctkokklty", "ppoyrlrokplp", "mgtgryvrmytm", "bmmpcoptlvyt", "rbcbkklkgbym", "", "", "", ""),
        // H88 (seed 900087)
        listOf("boylvvycrcgp", "pgctogboocop", "lgmgppvkrbvk", "vyctytmookty", "ctmptvtrmrlo", "yrglmbtbbvkl", "pmyygbmbbloo", "lylvgkprctlv", "rtkoyccltppv", "bpmccrkkkgbk", "lrkmvcmlrvpy", "kmgbmtgrrgyo", "", "", "", ""),
        // H89 (seed 900088)
        listOf("oobtpllrkrrc", "byrygpmlpbkb", "kokgyylgtlok", "ombccrbgmmvv", "bmoltmgyooyc", "vgopyglptmrk", "bvllovtlbpkk", "vggvtbccpvpr", "pptvrypbykck", "gpbtgtmtgvmk", "tvrcrmomrvlt", "ccyylccymokr", "", "", "", ""),
        // H90 (seed 900089)
        listOf("olggytgktopp", "krgccrkvtmpp", "yopybokoytmb", "cmovorboobrm", "rbvvvgkocvmy", "mvlbmybtcbtc", "prpclygbvryb", "kltklrrtbkmv", "ktvlkromyctm", "ylrggpoyymvc", "plcmtlgpkvbg", "ckgltgplrlpc", "", "", "", ""),
        // H91 (seed 900090)
        listOf("mbkcmbmgoplp", "clkrrktovykk", "vplttgklmttt", "moplpktvbolc", "rlyokvrpbmrc", "lcgovrcomvov", "bbbyygyvpolb", "glcpbybyykmr", "optglrcvlcrg", "rkvckgmkpcgg", "vrypytgbmtbr", "mpgmtvyotyco", "", "", "", ""),
        // H92 (seed 900091)
        listOf("mkgmmytbrvrl", "lpkkgptyttom", "ylprocmpbrpb", "yvkmgbklvcyk", "koblvcvtyorv", "pmvolmtobkcb", "ygvtlglomtlb", "poglyrkygyvc", "rtpccttovbgr", "kogtccpvycrb", "mogpkbbrpgvm", "clpcogryklrm", "", "", "", ""),
        // H93 (seed 900092)
        listOf("lvplmmcbgtot", "trkpyvkvgtkr", "kobyclkbybto", "pycmlrlyykbc", "gcrpbtorrytp", "vgrpgbytoolm", "pgmptlbgkbvl", "rcybmkovrllp", "yolgoymgbpgm", "rckgcrrvomvv", "pcotvmvpvmkc", "lcbtkcgomytk", "", "", "", ""),
        // H94 (seed 900093)
        listOf("lggtkycbtgyl", "ylbtbygrvock", "rryotyotvrgr", "ccpkkppyykoo", "btpctmypovkm", "okkpmrvbklvk", "bolvbgbpotro", "ptmlpbpccvvb", "cormcllmlrrl", "vtvccvmymmpb", "ggtlvgmcyygb", "rgotmprgkmkl", "", "", "", ""),
        // H95 (seed 900094)
        listOf("kyggrlbcoktt", "vlyytpmpmytm", "krorbgcgrrmm", "rprlckmvvocm", "kyyopvvmkvbt", "pvktllybmklp", "pproclmvbpor", "yovcbvobctcg", "ooyctgygbggk", "rlgycbgckvpt", "bbrpktlvptmy", "lctolgrolmkb", "", "", "", ""),
        // H96 (seed 900095)
        listOf("vllrrymbgktk", "ttolcoypbmtr", "krlctrlcprko", "gpovkmogmgmy", "loomppkpgykm", "tpromvtkmlrp", "kpglttbbpbmv", "vcgyroykcygb", "kvbclggvtrgo", "vvlytgycblcr", "vvvbompbccyb", "cmylbtcyorpk", "", "", "", ""),
        // H97 (seed 900096)
        listOf("mgtborycrctm", "ppgyvbttcpcp", "glbcyotytbob", "ccgkrvttmcop", "mypogvrorcvv", "kgrtkllbbrpy", "lllryyvroltr", "vygvpmkplotc", "kkllkggrgcgo", "cbkmkmvmbvpk", "mbgytblblvpv", "ooromkmyypkm", "", "", "", ""),
        // H98 (seed 900097)
        listOf("lcltyoycgvlg", "tlgcyymyckko", "pockcrgpbbmo", "mrompcmocpbp", "bmvltovrmcly", "byrvtmkpvprp", "vbyvlgtlvtpo", "rltrvvggoolg", "vktkkbmryrlm", "gtbkgptbycmc", "rgbkkytrptoc", "bmkobplyvrkg", "", "", "", ""),
        // H99 (seed 900098)
        listOf("ygykmlvkyctb", "mpcrmkrmvomp", "kcoorvvpvpto", "lypgylmmrbgy", "gtolykkgglyb", "pgrktlgttbbp", "cbcpvvymrlkb", "mgptorkvcocl", "lcybvbtlobyc", "lpkgrrbvlokc", "otbrptgvycmr", "ototrmkpgvmc", "", "", "", ""),
        // H100 (seed 900099)
        listOf("yrtltrcobbrr", "vlkyvllckotr", "gyrtymcbyklp", "vkycpcgbvmvl", "pctrbpkylmtg", "kcpylgbbtgmy", "mokppyktgomp", "bbpotvkrorgv", "olrvovbmvtgg", "ccoptclolkoy", "vomgpryplbvm", "mmgckmtrkcbg", "", "", "", ""),
    )
}
