package uk.co.tjcdeveloper.opencoloursort.tools

import uk.co.tjcdeveloper.opencoloursort.game.LevelGenerator
import uk.co.tjcdeveloper.opencoloursort.levels.PackPlan
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

/**
 * Codegen tool, not a test: generates the shipped level set from [PackPlan]
 * and writes GeneratedLevels.kt into the main source tree. Run explicitly:
 *
 *   ./gradlew :app:testDebugUnitTest --tests "*BakeLevelsTool*" -PbakeLevels=true
 *
 * It is skipped in normal test runs. Each classic pack draws seeds from its
 * own base (pack index N -> 10000 * (N + 1)) so editing one pack's plan
 * never reshuffles the others.
 */
class BakeLevelsTool {

    @Test
    fun bake() {
        assumeTrue(System.getProperty("bakeLevels") == "true")

        val out = StringBuilder()
        out.appendLine("package uk.co.tjcdeveloper.opencoloursort.levels")
        out.appendLine()
        out.appendLine("/**")
        out.appendLine(" * GENERATED by BakeLevelsTool from PackPlan - do not edit by hand.")
        out.appendLine(" * Every level is solver-verified solvable; classic levels sit inside")
        out.appendLine(" * their PackPlan min-moves and dead-state bands.")
        out.appendLine(" * Encoding: one string per tube, colour keys bottom -> top.")
        out.appendLine(" */")
        out.appendLine("object GeneratedLevels {")
        out.appendLine("    /** Packs 1-10 in play order, 40 levels each. */")
        out.appendLine("    val classic: List<List<List<String>>> = listOf(")

        for ((packIndex, plan) in PackPlan.classicPacks.withIndex()) {
            out.appendLine("        // Pack ${packIndex + 1} - ${plan.name}")
            out.appendLine("        listOf(")
            var seedBase = 10_000L * (packIndex + 1)
            var level = 1
            for (segment in plan.segments) {
                repeat(segment.count) {
                    val generated = LevelGenerator.generate(segment.spec, seedBase, maxAttempts = 5_000)
                        ?: error("${plan.name} L$level: no board found for ${segment.spec}")
                    seedBase = generated.seed + 1
                    val tubes = generated.encoded.joinToString(", ") { "\"$it\"" }
                    val dead = "%.1f".format(generated.deadPercent)
                    out.appendLine(
                        "            // P${packIndex + 1} L$level: ${segment.spec.colours}c " +
                            "${segment.spec.emptyTubes}e, min ${generated.minMoves} moves, " +
                            "dead $dead% (seed ${generated.seed})",
                    )
                    out.appendLine("            listOf($tubes),")
                    println("${plan.name} L$level: min=${generated.minMoves} dead=$dead% seed=${generated.seed}")
                    level++
                }
            }
            out.appendLine("        ),")
        }
        out.appendLine("    )")

        out.appendLine("    val hard = listOf(")
        var hardSeed = 900_000L
        for (level in 1..PackPlan.HARD_LEVELS) {
            val generated = LevelGenerator.generateHard(
                PackPlan.HARD_COLOURS, PackPlan.HARD_EMPTY, PackPlan.HARD_CAPACITY, hardSeed,
            ) ?: error("Hard level $level: no board found")
            hardSeed = generated.seed + 1
            val tubes = generated.encoded.joinToString(", ") { "\"$it\"" }
            out.appendLine("        // H$level (seed ${generated.seed})")
            out.appendLine("        listOf($tubes),")
            println("hard H$level: seed=${generated.seed}")
        }
        out.appendLine("    )")
        out.appendLine("}")

        val target = File(
            System.getProperty("bakeLevels.out")
                ?: "src/main/java/uk/co/tjcdeveloper/opencoloursort/levels/GeneratedLevels.kt",
        )
        target.parentFile.mkdirs()
        target.writeText(out.toString())
        println("Wrote ${target.absolutePath}")
    }
}
